/**
 * Copyright (c) 2003-2011 The Apereo Foundation
 *
 * Licensed under the Educational Community License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *             http://opensource.org/licenses/ecl2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.sakaiproject.citation.impl.openurl;

/**
 * These are some example OpenURLs generated by Primo for different types.
 * These all came from the Journal Search rather than the Oxford holdings.
 * All of them don't specify what format they are in.
 * 
 * @author buckett
 * 
 */
public interface SamplePrimoOpenURLs {

	String ARTICLE = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A11%3A26IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-crossref&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=article&" +
			"rft.atitle=Patent&rft.jtitle=Metal%20Powder%20Report&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&rft.auinitm=&" +
			"rft.ausuffix=&rft.au=&rft.aucorp=&rft.date=199206&rft.volume=47&rft.issue=6&rft.part=&rft.quarter=&rft.ssn=&rft.spage=59" +
			"&rft.epage=61&rft.pages=&rft.artnum=&rft.issn=00260657&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&" +
			"rft_id=info:doi/10.1016/0026-0657(92)91523-M&rft.object_id=&rft_dat=%3Ccrossref%3E10.1016/0026-0657(92)91523-M%3C/crossref%3E&rft.eisbn=";
	String NEWSPAPER = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A13%3A37IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-accessible_archives&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=unknown" +
			"&rft.atitle=AZA%20ARNOLD,%20PATENT%20AGENT%20AZA%20ARNOLD,%20PATENT%20AGENT,%20Furnishes%20Drawings,%20Specifications," +
			"	%20Caveats,%20Conveyances,%20PROCURES%20PATENTS,%20And%20attends%20to%20all%20business%20usually%20required%20to%20" +
			"	the%20transacted%20with%20the%20Patent%20Office.%20REFERENCES:&" +
			"rft.jtitle=THE%20NATIONAL%20ERA&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=&" +
			"rft.aucorp=&rft.date=18590310&rft.volume=XIII&rft.issue=636&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&" +
			"rft.pages=&rft.artnum=&rft.issn=&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&" +
			"rft_dat=%3Caccessible_archives%3EFR1859031026%3C/accessible_archives%3E&rft.eisbn=";
	String OTHER = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A14%3A39IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-oxford&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=unknown&" +
			"rft.atitle=Eustachian%20valve%20interfering%20with%20transcatheter%20closure%20of%20patent%20foramen%20ovale&" +
			"rft.jtitle=European%20Journal%20of%20Echocardiography&rft.btitle=&rft.aulast=Roelandt&rft.auinit=&rft.auinit1=&" +
			"rft.auinitm=&rft.ausuffix=&rft.au=Roelandt,%20Philip&rft.aucorp=&rft.date=200707&rft.volume=9&rft.issue=1&rft.part=&" +
			"rft.quarter=&rft.ssn=&rft.spage=158&rft.epage=159&rft.pages=158-159&rft.artnum=&rft.issn=1525-2167&rft.eissn=1532-2114&" +
			"rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/10.1016/j.euje.2007.05.006&rft.object_id=&" +
			"rft_dat=%3Coxford%3E10.1016/j.euje.2007.05.006%3C/oxford%3E&rft.eisbn=";
	String TEXT = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A15%3A25IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-cambridge&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=unknown&" +
			"rft.atitle=Complete%20transcatheter%20closure%20of%20a%20patent%20arterial%20duct%20with%20subsequent%20haemolysis&" +
			"rft.jtitle=Cardiology%20in%20the%20Young&rft.btitle=&rft.aulast=Cace&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&" +
			"rft.au=Cace,%20Neven&rft.aucorp=&rft.date=20100325201008&rft.volume=20&rft.issue=4&rft.part=&rft.quarter=&rft.ssn=&" +
			"rft.spage=462&rft.epage=464&rft.pages=&rft.artnum=&rft.issn=1047-9511&rft.eissn=1467-1107&rft.isbn=&rft.sici=&rft.coden=&" +
			"rft_id=info:doi/10.1017/S1047951110000326&rft.object_id=&rft_dat=%3Ccambridge%3ES1047951110000326%3C/cambridge%3E&rft.eisbn=";
	String BOOK = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-12-01T10%3A37%3A06IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Journal-dawson&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=book&" +
			"rft.atitle=&rft.jtitle=&rft.btitle=Patent%20searching:%20tools%20%26%20techniques&rft.aulast=&rft.auinit=&rft.auinit1=&" +
			"rft.auinitm=&rft.ausuffix=&rft.au=[edited%20By]%20David%20Hunt,%20Long%20Nguyen,%20Matthew%20Rodgers.&rft.aucorp=&" +
			"rft.volume=&rft.issue=&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&rft.pages=&rft.artnum=&rft.issn=&" +
			"ft.eissn=&rft.isbn=047178379X&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&" +
			"rft_bat=%3Cdawson%3E9780470116838%3C/dawson%3E&rft.eisbn=9780470116838";
	String REVIEW = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A17%3A05IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-cambridge&rft_val_fmt=info:ofi/fmt:kev:mtx:book&" +
			"rft.genre=unknown&" +
			"rft.atitle=Children%20of%20the%20Queen%27s%20Revels:%20A%20Jacobean%20Theatre%20Repertory%20(Book%20Review)&" +
			"rft.jtitle=Theatre%20Research%20International&rft.btitle=&rft.aulast=PRICE&rft.auinit=&rft.auinit1=&rft.auinitm=&" +
			"rft.ausuffix=&rft.au=PRICE,%20VICTORIA%20E&rft.aucorp=&rft.date=200707&rft.volume=32&rft.issue=2&rft.part=&rft.quarter=&" +
			"rft.ssn=&rft.spage=225&rft.epage=225&rft.pages=&rft.artnum=&rft.issn=0307-8833&rft.eissn=1474-0672&rft.isbn=&rft.sici=&" +
			"rft.coden=&rft_id=info:doi/10.1017/S0307883306002653&rft.object_id=&" +
			"rft_dat=%3Ccambridge%3ES0307883306002653%3C/cambridge%3E&rft.eisbn=";
	String JOURNAL = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A17%3A48IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-adam_matthew&rft_val_fmt=info:ofi/fmt:kev:mtx:&" +
			"rft.genre=journal&rft.atitle=&rft.jtitle=Kingston%20Journal&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&" +
			"rft.auinitm=&rft.ausuffix=&rft.au=&rft.aucorp=&rft.date=1789&rft.volume=&rft.issue=&rft.part=&rft.quarter=&" +
			"rft.ssn=&rft.spage=&rft.epage=&rft.pages=&rft.artnum=&rft.issn=&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&" +
			"rft_id=info:doi/&rft.object_id=&rft_dat=%3Cadam_matthew%3E212652%3C/adam_matthew%3E&rft.eisbn=";
	String LEGAL = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A18%3A27IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-eric&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=unknown&" +
			"rft.atitle=Patent%20Policy.%20Universities%27%20Research%20Efforts%20under%20Public%20Law%2096-517.%20" +
			" Report%20to%20the%20Honorable%20Robert%20Dole,%20United%20States%20Senate.&" +
			"rft.jtitle=&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=&rft.aucorp=&" +
			"rft.date=198604&rft.volume=&rft.issue=&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&rft.pages=&rft.artnum=&" +
			"rft.issn=&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&" +
			"rft_dat=%3Ceric%3EED271324%3C/eric%3E&rft.eisbn=";
	String DISSERTATION = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A19%3A07IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-cambridge&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=unknown&" +
			"rft.atitle=Thomas%20Blanchard%27s%20Patent%20Management&rft.jtitle=The%20Journal%20of%20Economic%20History&" +
			"rft.btitle=&rft.aulast=Cooper&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=Cooper,%20Carolyn%20C&rft.aucorp=&" +
			"rft.date=198706&rft.volume=47&rft.issue=2&rft.part=&rft.quarter=&rft.ssn=&rft.spage=487&rft.epage=488&rft.pages=&" +
			"rft.artnum=&rft.issn=0022-0507&rft.eissn=1471-6372&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/10.1017/S002205070004821X&" +
			"rft.object_id=&rft_dat=%3Ccambridge%3ES002205070004821X%3C/cambridge%3E&rft.eisbn=";
	String IMAGE = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2010-11-26T17%3A19%3A57IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-informit&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=unknown&" +
			"rft.atitle=Cocktail%20Hour&rft.jtitle=&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&" +
			"rft.au=&rft.aucorp=&rft.date=2008&rft.volume=&rft.issue=Nov/Dec%202008&rft.part=&rft.quarter=&rft.ssn=&rft.spage=58&" +
			"rft.epage=63&rft.pages=&rft.artnum=&rft.issn=1836-7526&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/&" +
			"rft.object_id=&rft_dat=%3Cinformit%3E750082611527469%3C/informit%3E&rft.eisbn=";
	
	String CORRECT_JOURNAL = "http://oxfordsfx-direct.hosted.exlibrisgroup.com/oxford?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&" +
			"ctx_tim=2011-04-21T10%3A02%3A00IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&" +
			"rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Journal-UkOxU&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.genre=journal&" +
			"rft.atitle=&rft.jtitle=Theory%20and%20practice%20of%20logic%20programming&rft.btitle=&rft.aulast=&rft.auinit=&rft.auinit1=&" +
			"rft.auinitm=&rft.ausuffix=&rft.au=&rft.aucorp=&rft.volume=&rft.issue=&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&" +
			"rft.pages=&rft.artnum=&rft.issn=1475-3081&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&" +
			"rft_bat=%3CUkOxU%3EUkOxUb16836813%3C/UkOxU%3E&rft.eisbn=&rft_id=info:oai/&" +
			"rft_id=http%3A%2F%2Fsolo.bodleian.ox.ac.uk%2Fprimo_library%2Flibweb%2Faction%2Fdisplay.do%3Fdoc%3DUkOxUUkOxUb16836813%26vid%3DOXVU1%26fn%3Ddisplay%26displayMode%3Dfull";
	
	// This one was working correctly when importing into WebLearn
	String WORKING_IMPORT = "https://weblearn.ox.ac.uk/savecite/0b3fca24-e82a-4cf8-8480-7daa596a6ae0?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&ctx_tim=2011-06-10T14%3A31%3A48IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Journal-UkOxU&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=book&rft.atitle=&rft.jtitle=&rft.btitle=Linux%20in%20a%20nutshell&rft.aulast=Siever&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=Siever,%20Ellen&rft.aucorp=&rft.volume=&rft.issue=&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&rft.pages=&rft.artnum=&rft.issn=&rft.eissn=&rft.isbn=0596004826&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&rft_dat=%3CUkOxU%3EUkOxUb15585873%3C/UkOxU%3E&rft.eisbn=&rft_id=http%3A%2F%2Fsolo.bodleian.ox.ac.uk%2Fprimo_library%2Flibweb%2Faction%2Fdisplay.do%3Fdoc%3DUkOxUUkOxUb15585873%26vid%3DOXVU1%26fn%3Ddisplay%26displayMode%3Dfull&rft_id=info:oai/&rft_id=http%3A%2F%2Fsolo.bodleian.ox.ac.uk%2Fprimo_library%2Flibweb%2Faction%2Fdisplay.do%3Fdoc%3DUkOxUUkOxUb15585873%26vid%3DOXVU1%26fn%3Ddisplay%26displayMode%3Dfull";
	
	// This URL was failing to have it's IDs set correctly.
	String BROKEN_IMPORT = "https://weblearn.ox.ac.uk/savecite/0b3fca24-e82a-4cf8-8480-7daa596a6ae0?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&ctx_tim=2011-06-10T14%3A31%3A48IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Journal-UkOxU&rft_val_fmt=info:ofi/fmt:kev:mtx:book&rft.genre=book&rft.atitle=&rft.jtitle=&rft.btitle=Linux%20in%20a%20nutshell&rft.aulast=Siever&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=&rft.aucorp=&rft.volume=&rft.issue=&rft.part=&rft.quarter=&rft.ssn=&rft.spage=&rft.epage=&rft.pages=&rft.artnum=&rft.issn=&rft.eissn=&rft.isbn=9780596154486&rft.sici=&rft.coden=&rft_id=info:doi/&rft.object_id=&rft_dat=%3CUkOxU%3EUkOxUb17140770%3C/UkOxU%3E&rft.eisbn=&rft_id=http%3A%2F%2Fsolo.bodleian.ox.ac.uk%2Fprimo_library%2Flibweb%2Faction%2Fdisplay.do%3Fdoc%3DUkOxUUkOxUb17140770%26vid%3DOXVU1%26fn%3Ddisplay%26displayMode%3Dfull&rft_id=info:oai/&rft_id=http%3A%2F%2Fsolo.bodleian.ox.ac.uk%2Fprimo_library%2Flibweb%2Faction%2Fdisplay.do%3Fdoc%3DUkOxUUkOxUb17140770%26vid%3DOXVU1%26fn%3Ddisplay%26displayMode%3Dfull";
}
