alter table SEC_PARTICIPATION_T drop constraint FKF99100A8CB25818C;
alter table SEC_SECTION_T drop constraint FK841BEACCFD775FBF;
alter table SEC_SECTION_T drop constraint FK841BEACC91B;
alter table SEC_COURSE_T drop constraint FKAD8BDD7E91B;
drop table SEC_PARTICIPATION_T if exists;
drop table SEC_SECTION_T if exists;
drop table SEC_COURSE_T if exists;
drop table SEC_LEARNING_CONTEXT_T if exists;
create table SEC_PARTICIPATION_T (
   ID bigint generated by default as identity (start with 1),
   DISCR integer not null,
   VERSION integer not null,
   LEARNING_CONTEXT_ID bigint not null,
   USER_ID varchar(255) not null,
   PARTICIPATION_UUID varchar(255) not null,
   STATUS varchar(255),
   unique (PARTICIPATION_UUID)
);
create table SEC_SECTION_T (
   ID bigint not null,
   COURSE_ID bigint,
   LOCATION varchar(255),
   CATEGORY varchar(255),
   MAX_ENROLLMENTS integer,
   MONDAY bit,
   TUESDAY bit,
   WEDNESDAY bit,
   THURSDAY bit,
   FRIDAY bit,
   SATURDAY bit,
   SUNDAY bit,
   START_TIME time,
   END_TIME time,
   primary key (ID)
);
create table SEC_COURSE_T (
   ID bigint not null,
   SITE_CONTEXT varchar(255) not null,
   EXTERNAL_MGMT bit,
   SELF_REG bit,
   SELF_SWITCH bit,
   primary key (ID),
   unique (SITE_CONTEXT)
);
create table SEC_LEARNING_CONTEXT_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   LEARNING_CONTEXT_UUID varchar(255) not null,
   TITLE varchar(255) not null,
   unique (LEARNING_CONTEXT_UUID)
);
alter table SEC_PARTICIPATION_T add constraint FKF99100A8CB25818C foreign key (LEARNING_CONTEXT_ID) references SEC_LEARNING_CONTEXT_T;
alter table SEC_SECTION_T add constraint FK841BEACCFD775FBF foreign key (COURSE_ID) references SEC_COURSE_T;
alter table SEC_SECTION_T add constraint FK841BEACC91B foreign key (ID) references SEC_LEARNING_CONTEXT_T;
alter table SEC_COURSE_T add constraint FKAD8BDD7E91B foreign key (ID) references SEC_LEARNING_CONTEXT_T;