-----------------------------------------------------------------------------
-- SAKAI_CONFIG_ITEM - KNL-1063 - ORACLE
-----------------------------------------------------------------------------

CREATE TABLE SAKAI_CONFIG_ITEM (
	ID				NUMBER(20) NOT NULL,
	NODE			VARCHAR2(255),
	NAME			VARCHAR2(255) NOT NULL,
	VALUE			CLOB,  
	RAW_VALUE		CLOB,
	TYPE			VARCHAR2(255) NOT NULL,
	DEFAULT_VALUE	CLOB,
	DESCRIPTION		CLOB,
	SOURCE			VARCHAR2(255) DEFAULT NULL,
	DEFAULTED		CHAR(1) NOT NULL,
	REGISTERED		CHAR(1) NOT NULL,
	SECURED			CHAR(1) NOT NULL,
	DYNAMIC			CHAR(1) NOT NULL,
	CREATED			TIMESTAMP NOT NULL,
	MODIFIED		TIMESTAMP NOT NULL,
	POLL_ON			TIMESTAMP DEFAULT NULL
);

ALTER TABLE SAKAI_CONFIG_ITEM
	ADD  ( PRIMARY KEY (ID) );

CREATE INDEX SCI_NODE_IDX ON SAKAI_CONFIG_ITEM (NODE ASC);
CREATE INDEX SCI_NAME_IDX ON SAKAI_CONFIG_ITEM (NAME ASC);

CREATE SEQUENCE SAKAI_CONFIG_ITEM_S;
