<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%@ taglib uri="http://myfaces.apache.org/tomahawk" prefix="t" %>
<%-- This file generated by Sakai App Builder --%>
<f:view>
<f:loadBundle basename="messages" var="msgs"/>
	<sakai:view_container title="Signup Tool">
		<style type="text/css">
			@import url("/sakai-signup-tool/css/signupStyle.css");
		</style>
		<script TYPE="text/javascript" LANGUAGE="JavaScript" src="/sakai-signup-tool/js/signupScript.js"></script>
		
		<sakai:view_content>
			<h:outputText value="#{msgs.event_error_alerts} #{errorMessageUIBean.errorMessage}" styleClass="alertMessage" escape="false" rendered="#{errorMessageUIBean.error}"/>      							
			
			<h:form id="meeting">
				<sakai:view_title value="#{msgs.event_step4_page_title}" rendered="#{!NewSignupMeetingBean.announcementType}"/>
					
				<h:panelGrid columns="3" styleClass="meetingTypeTable" columnClasses="timeSelectTab" rendered="#{!NewSignupMeetingBean.announcementType}">								
					<h:outputText value="#{msgs.event_signup_begins}" escape="false"/>
					<h:panelGroup>
						<h:inputText id="signupBegins" value="#{NewSignupMeetingBean.signupBegins}" size="3" required="true">
							<f:validateLongRange minimum="0" maximum="1000"/>
						</h:inputText>
						<h:selectOneMenu value="#{NewSignupMeetingBean.signupBeginsType}" >
							<f:selectItem itemValue="minutes" itemLabel="#{msgs.label_minutes}"/>
							<f:selectItem itemValue="hours" itemLabel="#{msgs.label_hours}"/>
							<f:selectItem itemValue="days" itemLabel="#{msgs.label_days}"/>
						</h:selectOneMenu>
					</h:panelGroup>
					<h:panelGroup>
						<h:outputText value="#{msgs.before_event_start}" escape="false"/>
						<h:message for="signupBegins" errorClass="alertMessageInline" />
					</h:panelGroup>
					
					<h:outputText value="#{msgs.event_signup_deadline2}" escape="false"/>
					<h:panelGroup>
						<h:inputText id="signupDeadline" value="#{NewSignupMeetingBean.deadlineTime}" size="3" required="true">
							<f:validateLongRange minimum="0" maximum="1000"/>
						</h:inputText>
						<h:selectOneMenu value="#{NewSignupMeetingBean.deadlineTimeType}" >
							<f:selectItem itemValue="minutes" itemLabel="#{msgs.label_minutes}"/>
							<f:selectItem itemValue="hours" itemLabel="#{msgs.label_hours}"/>
							<f:selectItem itemValue="days" itemLabel="#{msgs.label_days}"/>
						</h:selectOneMenu>
					</h:panelGroup>
					<h:panelGroup>
						<h:outputText value="#{msgs.before_event_end}" escape="false"/>
						<h:message for="signupDeadline" errorClass="alertMessageInline" />
					</h:panelGroup>
				</h:panelGrid>
			
			 	<sakai:view_title value="#{msgs.event_site_group_availability}" />			

				<h:panelGrid columns="1" styleClass="meetingTypeTable">
					<h:outputText value="#{msgs.event_current_site}" style="font-weight:bold;" escape="false"/>
					<h:panelGroup>
						<h:selectBooleanCheckbox id="siteSelection" value="#{NewSignupMeetingBean.currentSite.selected}" disabled="#{!NewSignupMeetingBean.currentSite.allowedToCreate}"
							onclick="currentSiteSelection();"/>
						<h:outputText value="#{NewSignupMeetingBean.currentSite.signupSite.title}" styleClass="longtext"/>
					</h:panelGroup>
					<h:dataTable id="currentSiteGroups" value="#{NewSignupMeetingBean.currentSite.signupGroupWrappers}" var="currentGroup" styleClass="meetingTypeTable">
						<h:column>
							<h:panelGroup>
								<h:selectBooleanCheckbox id="groupSelection" value="#{currentGroup.selected}" disabled="#{!currentGroup.allowedToCreate}"/>
								<h:outputText value="#{currentGroup.signupGroup.title}" styleClass="longtext"/>
							</h:panelGroup>
						</h:column>
					</h:dataTable>
					
					<h:panelGroup>
						<h:outputText value="<span id='imageOpen_otherSites' style='display:none'>"  escape="false"/>
	   	    				<h:graphicImage value="/images/open.gif"  alt="open" style="border:none" onclick="showDetails()" />
	   	    			<h:outputText value="</span>" escape="false" />
	   	    			
	   	    			<h:outputText value="<span id='imageClose_otherSites'>"  escape="false"/>
	   	    				<h:graphicImage value="/images/closed.gif" alt="close" style="border:none" onclick="showDetails()"/>
	   	    			<h:outputText value="</span>" escape="false" />
						<h:outputLabel value="#{msgs.event_other_sites}" style='font-weight:bold; cursor:default;' onmouseover='style.color=\"blue\"' onmouseout='style.color=\"black\"'/>
					</h:panelGroup>	
    	    		<h:panelGroup>
    	    			<h:outputText value="<div id='otherSites' style='display:none'>" escape="false"/>	
						<h:dataTable id="userSites" value="#{NewSignupMeetingBean.otherSites}" var="site" styleClass="meetingTypeTable">
							<h:column>
								<h:panelGroup>
									<h:selectBooleanCheckbox id="otherSitesSelection" value="#{site.selected}" disabled="#{!site.allowedToCreate}" onclick="otherUserSitesSelection();"/>
									<h:outputText value="#{site.signupSite.title}" styleClass="editText" escape="false"/>
								</h:panelGroup>
								<h:dataTable id="userGroups" value="#{site.signupGroupWrappers}" var="group" styleClass="meetingTypeTable">
									<h:column>
										<h:panelGroup>
											<h:selectBooleanCheckbox id="otherGroupsSelection" value="#{group.selected}" disabled="#{!group.allowedToCreate}" onclick=""/>
											<h:outputText value="#{group.signupGroup.title}" styleClass="longtext"/>
										</h:panelGroup>
									</h:column>
								
								</h:dataTable>
							</h:column>
						</h:dataTable>
						<h:outputText value="</div>" escape="false" />
					</h:panelGroup>	
				
				</h:panelGrid>
					
				<h:inputHidden value="step4" binding="#{NewSignupMeetingBean.currentStepHiddenInfo}"/>
				<sakai:button_bar>
					<h:commandButton id="goNextPage" action="#{NewSignupMeetingBean.goNext}" actionListener="#{NewSignupMeetingBean.validateNewMeeting}"  value="#{msgs.next_button}"/> 
					<h:commandButton id="goBack" action="#{NewSignupMeetingBean.goBack}" value="#{msgs.goback_button}"/>
					<h:commandButton id="Cancel" action="#{NewSignupMeetingBean.processCancel}" value="#{msgs.cancel_button}"  immediate="true"/>  
                </sakai:button_bar>

			 </h:form>
  		</sakai:view_content>	
	</sakai:view_container>
	<f:verbatim>
		<script>
			currentSiteSelection();
			otherUserSitesSelection();
			
			function showDetails(){
				var detailId = document.getElementById('otherSites');
				if(detailId.style.display=="none")
					detailId.style.display="";
				else
					detailId.style.display="none";
		
				var imageOpen = document.getElementById('imageOpen_otherSites');	
				if(imageOpen.style.display=="none")
					imageOpen.style.display="";
				else
					imageOpen.style.display="none";
		
				var imageClose = document.getElementById('imageClose_otherSites');	
				if(imageClose.style.display=="none")
					imageClose.style.display="";
				else
				imageClose.style.display="none";					
			}
			
		</script>
	</f:verbatim>	
</f:view> 
