CREATE TABLE `MFR_EMAIL_NOTIFICATION_T` (
  `ID` bigint(20) NOT NULL auto_increment,
  `VERSION` int(11) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  `CONTEXT_ID` varchar(255) NOT NULL,
  `NOTIFICATION_LEVEL` varchar(255) NOT NULL,
  PRIMARY KEY  (`ID`)
);

 
CREATE INDEX MFR_EMAIL_USER_ID_I ON  MFR_EMAIL_NOTIFICATION_T(USER_ID);
CREATE INDEX  MFR_EMAIL_CONTEXT_ID_I ON  MFR_EMAIL_NOTIFICATION_T(CONTEXT_ID);