/**
 * VeriCiteLmsApiV1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.sakaiproject.contentreview.vericite.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ExternalContentUploadInfo
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-30T12:19:34.237Z")
public class ExternalContentUploadInfo   {
  @SerializedName("externalContentId")
  private String externalContentId = null;

  @SerializedName("urlPost")
  private String urlPost = null;

  @SerializedName("filePath")
  private String filePath = null;

  @SerializedName("contentLength")
  private Integer contentLength = null;

  @SerializedName("contentType")
  private String contentType = null;

  public ExternalContentUploadInfo externalContentId(String externalContentId) {
    this.externalContentId = externalContentId;
    return this;
  }

   /**
   * ID used to ID the uploaded file
   * @return externalContentId
  **/
  @ApiModelProperty(example = "null", value = "ID used to ID the uploaded file")
  public String getExternalContentId() {
    return externalContentId;
  }

  public void setExternalContentId(String externalContentId) {
    this.externalContentId = externalContentId;
  }

  public ExternalContentUploadInfo urlPost(String urlPost) {
    this.urlPost = urlPost;
    return this;
  }

   /**
   * URL to submit the attachment to
   * @return urlPost
  **/
  @ApiModelProperty(example = "null", value = "URL to submit the attachment to")
  public String getUrlPost() {
    return urlPost;
  }

  public void setUrlPost(String urlPost) {
    this.urlPost = urlPost;
  }

  public ExternalContentUploadInfo filePath(String filePath) {
    this.filePath = filePath;
    return this;
  }

   /**
   * The file path
   * @return filePath
  **/
  @ApiModelProperty(example = "null", value = "The file path")
  public String getFilePath() {
    return filePath;
  }

  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }

  public ExternalContentUploadInfo contentLength(Integer contentLength) {
    this.contentLength = contentLength;
    return this;
  }

   /**
   * The length of the file
   * @return contentLength
  **/
  @ApiModelProperty(example = "null", value = "The length of the file")
  public Integer getContentLength() {
    return contentLength;
  }

  public void setContentLength(Integer contentLength) {
    this.contentLength = contentLength;
  }

  public ExternalContentUploadInfo contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * The files content type
   * @return contentType
  **/
  @ApiModelProperty(example = "null", value = "The files content type")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalContentUploadInfo externalContentUploadInfo = (ExternalContentUploadInfo) o;
    return Objects.equals(this.externalContentId, externalContentUploadInfo.externalContentId) &&
        Objects.equals(this.urlPost, externalContentUploadInfo.urlPost) &&
        Objects.equals(this.filePath, externalContentUploadInfo.filePath) &&
        Objects.equals(this.contentLength, externalContentUploadInfo.contentLength) &&
        Objects.equals(this.contentType, externalContentUploadInfo.contentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalContentId, urlPost, filePath, contentLength, contentType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalContentUploadInfo {\n");
    
    sb.append("    externalContentId: ").append(toIndentedString(externalContentId)).append("\n");
    sb.append("    urlPost: ").append(toIndentedString(urlPost)).append("\n");
    sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
    sb.append("    contentLength: ").append(toIndentedString(contentLength)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

