/**
 * VeriCiteLmsApiV1
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.sakaiproject.contentreview.vericite.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.sakaiproject.contentreview.vericite.client.model.ExternalContentData;
import java.util.ArrayList;
import java.util.List;


/**
 * ReportMetaData
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-30T12:19:34.237Z")
public class ReportMetaData   {
  @SerializedName("userFirstName")
  private String userFirstName = null;

  @SerializedName("userLastName")
  private String userLastName = null;

  @SerializedName("userEmail")
  private String userEmail = null;

  @SerializedName("userRole")
  private String userRole = null;

  @SerializedName("assignmentTitle")
  private String assignmentTitle = null;

  @SerializedName("contextTitle")
  private String contextTitle = null;

  @SerializedName("externalContentData")
  private List<ExternalContentData> externalContentData = new ArrayList<ExternalContentData>();

  public ReportMetaData userFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
    return this;
  }

   /**
   * Users First Name
   * @return userFirstName
  **/
  @ApiModelProperty(example = "null", value = "Users First Name")
  public String getUserFirstName() {
    return userFirstName;
  }

  public void setUserFirstName(String userFirstName) {
    this.userFirstName = userFirstName;
  }

  public ReportMetaData userLastName(String userLastName) {
    this.userLastName = userLastName;
    return this;
  }

   /**
   * Users Last Name
   * @return userLastName
  **/
  @ApiModelProperty(example = "null", value = "Users Last Name")
  public String getUserLastName() {
    return userLastName;
  }

  public void setUserLastName(String userLastName) {
    this.userLastName = userLastName;
  }

  public ReportMetaData userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Users Email
   * @return userEmail
  **/
  @ApiModelProperty(example = "null", value = "Users Email")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public ReportMetaData userRole(String userRole) {
    this.userRole = userRole;
    return this;
  }

   /**
   * User Role
   * @return userRole
  **/
  @ApiModelProperty(example = "null", value = "User Role")
  public String getUserRole() {
    return userRole;
  }

  public void setUserRole(String userRole) {
    this.userRole = userRole;
  }

  public ReportMetaData assignmentTitle(String assignmentTitle) {
    this.assignmentTitle = assignmentTitle;
    return this;
  }

   /**
   * Title of Assignment
   * @return assignmentTitle
  **/
  @ApiModelProperty(example = "null", value = "Title of Assignment")
  public String getAssignmentTitle() {
    return assignmentTitle;
  }

  public void setAssignmentTitle(String assignmentTitle) {
    this.assignmentTitle = assignmentTitle;
  }

  public ReportMetaData contextTitle(String contextTitle) {
    this.contextTitle = contextTitle;
    return this;
  }

   /**
   * Title of Context
   * @return contextTitle
  **/
  @ApiModelProperty(example = "null", value = "Title of Context")
  public String getContextTitle() {
    return contextTitle;
  }

  public void setContextTitle(String contextTitle) {
    this.contextTitle = contextTitle;
  }

  public ReportMetaData externalContentData(List<ExternalContentData> externalContentData) {
    this.externalContentData = externalContentData;
    return this;
  }

  public ReportMetaData addExternalContentDataItem(ExternalContentData externalContentDataItem) {
    this.externalContentData.add(externalContentDataItem);
    return this;
  }

   /**
   * Get externalContentData
   * @return externalContentData
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<ExternalContentData> getExternalContentData() {
    return externalContentData;
  }

  public void setExternalContentData(List<ExternalContentData> externalContentData) {
    this.externalContentData = externalContentData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportMetaData reportMetaData = (ReportMetaData) o;
    return Objects.equals(this.userFirstName, reportMetaData.userFirstName) &&
        Objects.equals(this.userLastName, reportMetaData.userLastName) &&
        Objects.equals(this.userEmail, reportMetaData.userEmail) &&
        Objects.equals(this.userRole, reportMetaData.userRole) &&
        Objects.equals(this.assignmentTitle, reportMetaData.assignmentTitle) &&
        Objects.equals(this.contextTitle, reportMetaData.contextTitle) &&
        Objects.equals(this.externalContentData, reportMetaData.externalContentData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userFirstName, userLastName, userEmail, userRole, assignmentTitle, contextTitle, externalContentData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportMetaData {\n");
    
    sb.append("    userFirstName: ").append(toIndentedString(userFirstName)).append("\n");
    sb.append("    userLastName: ").append(toIndentedString(userLastName)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userRole: ").append(toIndentedString(userRole)).append("\n");
    sb.append("    assignmentTitle: ").append(toIndentedString(assignmentTitle)).append("\n");
    sb.append("    contextTitle: ").append(toIndentedString(contextTitle)).append("\n");
    sb.append("    externalContentData: ").append(toIndentedString(externalContentData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

