-----------------------------------------------------------------------------
-- SAKAI_SESSION
-----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS SAKAI_SESSION
(
	SESSION_ID VARCHAR (36),
	SESSION_SERVER VARCHAR (64),
	SESSION_USER VARCHAR (99),
	SESSION_IP VARCHAR (128),
	SESSION_HOSTNAME VARCHAR (255),
	SESSION_USER_AGENT VARCHAR (255),
	SESSION_START TIMESTAMP,
	SESSION_END TIMESTAMP,
	SESSION_ACTIVE tinyint(1),
	UNIQUE KEY `SAKAI_SESSION_INDEX` (`SESSION_ID`),
	KEY `SAKAI_SESSION_SERVER_INDEX` (`SESSION_SERVER`),
	KEY `SAKAI_SESSION_START_END_IE` (`SESSION_START`,`SESSION_END`,`SESSION_ID`),
	KEY `SESSION_ACTIVE_IE` (`SESSION_ACTIVE`)
);
