-----------------------------------------------------------------------------
-- SAKAI_SESSION
-----------------------------------------------------------------------------
CREATE TABLE SAKAI_SESSION
(
	SESSION_ID NVARCHAR (36),
	SESSION_SERVER NVARCHAR (64),
	[SESSION_USER] NVARCHAR (99),
   SESSION_IP NVARCHAR (128),
	SESSION_HOSTNAME NVARCHAR (255),
	SESSION_USER_AGENT NVARCHAR (255),
	SESSION_START DATETIME,
	SESSION_END DATETIME,
	SESSION_ACTIVE BIT
);

CREATE UNIQUE INDEX SAKAI_SESSION_INDEX ON SAKAI_SESSION
(
	SESSION_ID
);

CREATE INDEX SAKAI_SESSION_SERVER_INDEX ON SAKAI_SESSION
(
	SESSION_SERVER
);

CREATE INDEX SAKAI_SESSION_START_END_IE ON SAKAI_SESSION
(
	SESSION_START,
	SESSION_END,
	SESSION_ID
);

create index SESSION_ACTIVE_IE on SAKAI_SESSION 
(
	SESSION_ACTIVE
);
