-- SAK-16832
ALTER TABLE SAM_PUBLISHEDASSESSMENT_T ADD LASTNEEDRESUBMITDATE DATE NULL;

alter table SAM_ITEM_T add PARTIAL_CREDIT_FLAG bit NULL;
alter table SAM_PUBLISHEDITEM_T add PARTIAL_CREDIT_FLAG  bit NULL;
alter table SAM_ANSWER_T add PARTIAL_CREDIT float NULL;
alter table SAM_PUBLISHEDANSWER_T add PARTIAL_CREDIT float NULL; 
