-- SAM-666
alter table SAM_ASSESSFEEDBACK_T add FEEDBACKCOMPONENTOPTION integer default null;
update  SAM_ASSESSFEEDBACK_T set FEEDBACKCOMPONENTOPTION = 2;
alter table SAM_PUBLISHEDFEEDBACK_T add FEEDBACKCOMPONENTOPTION integer default null;
update  SAM_PUBLISHEDFEEDBACK_T set FEEDBACKCOMPONENTOPTION = 2;

alter table SAM_ASSESSMENTGRADING_T add LASTVISITEDPART integer default null;
alter table SAM_ASSESSMENTGRADING_T add LASTVISITEDQUESTION integer default null;

-- SAM-775
-- If you get an error when running this script, you will need to clean the duplicates first. Please refer to SAM-775.
create UNIQUE INDEX ASSESSMENTGRADINGID ON SAM_ITEMGRADING_T (ASSESSMENTGRADINGID,PUBLISHEDITEMID,PUBLISHEDITEMTEXTID,AGENTID,PUBLISHEDANSWERID);

