version: 2
jobs:
  build:
    working_directory: ~/sakai/
    docker:
      - image: maven:3.5
    steps:
      - checkout
      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: mvn test -B
