version: 2
jobs:
  build:
    working_directory: ~/sakai/
    docker:
      - image: maven:3.5
    steps:
      - checkout
      - restore_cache:
          key: MAVEN
      - run:
          name: Maven Install
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: 
          name: Maven Test
          command: mvn test -B
      - run:
          name: Clear Sakai Cache
          command: find ~/.m2/repository/org/sakaiproject -name \*-SNAPSHOT.\*  -delete
      - run:
          name: SetUp Test Reports
          command: mkdir -p $CIRCLE_TEST_REPORTS/junit/ && find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
      - save_cache:
          key: MAVEN
          paths:
            - ~/.m2/
