version: 2
jobs:
  build:
    working_directory: ~/sakai/
    docker:
      - image: maven:3.5
    steps:
      - checkout
      - restore_cache:
          key: MAVEN
      - run:
          name: Maven Install
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: 
          name: Maven Test
          command: mvn test -B
      - run:
          name: Delete org.sakaiproject
          command: rm -rf ~/.m2/repository/org/sakaiproject
      - save_cache:
          key: MAVEN
          paths:
            - ~/.m2/
