alter table lesson_builder_items add groupOwned bit;
alter table lesson_builder_items add ownerGroups varchar(4000);
alter table lesson_builder_items add attributeString longvarchar;
alter table lesson_builder_pages add groupid varchar(36);
    create table lesson_builder_qr_totals (
        id bigint generated by default as identity (start with 1),
        questionId bigint,
        responseId bigint,
        count bigint,
        primary key (id)
    );

    create table lesson_builder_question_responses (
        id bigint generated by default as identity (start with 1),
        timeAnswered timestamp not null,
        questionId bigint not null,
        userId varchar(255) not null,
        correct bit not null,
        shortanswer longvarchar,
        multipleChoiceId bigint,
        originalText longvarchar,
        overridden bit not null,
        points double,
        primary key (id)
    );

alter table lesson_builder_student_pages add groupid varchar(36);
