-----------------------------------------------------------------------------
-- SAKAI_CONFIG_ITEM
-----------------------------------------------------------------------------

CREATE TABLE SAKAI_CONFIG_ITEM (
	ID				BIGINT(20) NOT NULL AUTO_INCREMENT,
	NODE			VARCHAR(64) NOT NULL,
	NAME			VARCHAR(255) NOT NULL,
	VALUE			LONGVARCHAR,  
	RAW_VALUE		LONGVARCHAR,
	TYPE			VARCHAR(16) NOT NULL,
	DEFAULT_VALUE	LONGVARCHAR,
	DESCRIPTION		LONGVARCHAR,
	SOURCE			VARCHAR(255) DEFAULT NULL,
	DEFAULTED		BOOLEAN NOT NULL,
	REGISTERED		BOOLEAN NOT NULL,
	SECURED			BOOLEAN NOT NULL,
	DYNAMIC			BOOLEAN NOT NULL,
	CREATED			DATETIME NOT NULL,
	MODIFIED		DATETIME NOT NULL,
	POLL_ON			DATETIME DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX SCI_NODE_NAME_IDX ON SAKAI_CONFIG_ITEM
(
	NODE			ASC,
	NAME			ASC
);

