alter table MFR_LABEL_T drop constraint FKC6611543EA902104;
alter table MFR_LABEL_T drop constraint FKC661154344B127B6;
alter table MFR_AP_ACCESSORS_T drop constraint FKC8532ED796792399;
alter table MFR_AP_ACCESSORS_T drop constraint FKC8532ED721BCC7D2;
alter table MFR_AP_MODERATORS_T drop constraint FK75B43C0D21BCC7D2;
alter table MFR_AP_MODERATORS_T drop constraint FK75B43C0DC49D71A5;
alter table MFR_TOPIC_T drop constraint FK863DC0BEC6FDB1CF;
alter table MFR_TOPIC_T drop constraint FK863DC0BE7AFA22C2;
alter table MFR_TOPIC_T drop constraint FK863DC0BE20D91C10;
alter table MFR_MESSAGE_PERMISSIONS_T drop constraint FK750F9AFB17721828;
alter table MFR_MESSAGE_PERMISSIONS_T drop constraint FK750F9AFB51C89994;
alter table MFR_MESSAGE_PERMISSIONS_T drop constraint FK750F9AFBE581B336;
alter table MFR_AP_CONTRIBUTORS_T drop constraint FKA221A1F7737F309B;
alter table MFR_AP_CONTRIBUTORS_T drop constraint FKA221A1F721BCC7D2;
alter table MFR_MESSAGE_T drop constraint FK80C1A316FE0789EA;
alter table MFR_MESSAGE_T drop constraint FK80C1A3164FDCE067;
alter table MFR_PVT_MSG_USR_T drop constraint FKC4DE0E14FA8620E;
alter table MFR_ATTACHMENT_T drop constraint FK7B2D5CDE2AFBA652;
alter table MFR_ATTACHMENT_T drop constraint FK7B2D5CDEC6FDB1CF;
alter table MFR_ATTACHMENT_T drop constraint FK7B2D5CDE20D91C10;
alter table MFR_ATTACHMENT_T drop constraint FK7B2D5CDEFDEB22F9;
alter table MFR_ATTACHMENT_T drop constraint FK7B2D5CDEAD5AF852;
alter table MFR_MEMBERSHIP_ITEM_T drop constraint FKE03761CB6785AF85;
alter table MFR_MEMBERSHIP_ITEM_T drop constraint FKE03761CBC6FDB1CF;
alter table MFR_MEMBERSHIP_ITEM_T drop constraint FKE03761CB2AFBA652;
alter table MFR_MEMBERSHIP_ITEM_T drop constraint FKE03761CB925CE0F4;
alter table MFR_CONTROL_PERMISSIONS_T drop constraint FKA07CF1D1E581B336;
alter table MFR_CONTROL_PERMISSIONS_T drop constraint FKA07CF1D151C89994;
alter table MFR_CONTROL_PERMISSIONS_T drop constraint FKA07CF1D117721828;
alter table MFR_PRIVATE_FORUM_T drop constraint FKA9EE57544FDCE067;
alter table MFR_OPEN_FORUM_T drop constraint FKC17608474FDCE067;
drop table MFR_LABEL_T if exists;
drop table MFR_UNREAD_STATUS_T if exists;
drop table MFR_AP_ACCESSORS_T if exists;
drop table MFR_AP_MODERATORS_T if exists;
drop table MFR_TOPIC_T if exists;
drop table MFR_MESSAGE_PERMISSIONS_T if exists;
drop table MFR_PERMISSION_LEVEL_T if exists;
drop table MFR_AP_CONTRIBUTORS_T if exists;
drop table MFR_MESSAGE_T if exists;
drop table MFR_AREA_T if exists;
drop table MFR_PVT_MSG_USR_T if exists;
drop table MFR_ATTACHMENT_T if exists;
drop table MFR_ACTOR_PERMISSIONS_T if exists;
drop table MFR_MEMBERSHIP_ITEM_T if exists;
drop table MFR_CONTROL_PERMISSIONS_T if exists;
drop table MFR_PRIVATE_FORUM_T if exists;
drop table MFR_OPEN_FORUM_T if exists;
drop table MFR_MESSAGE_FORUMS_USER_T if exists;
drop table MFR_DATE_RESTRICTIONS_T if exists;
create table MFR_LABEL_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   KEY_C varchar(255) not null,
   VALUE_C varchar(255) not null,
   df_surrogateKey bigint,
   df_index_col integer,
   dt_surrogateKey bigint,
   dt_index_col integer
);
create table MFR_UNREAD_STATUS_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   TOPIC_C bigint not null,
   MESSAGE_C bigint not null,
   USER_C varchar(255) not null,
   READ_C bit not null
);
create table MFR_AP_ACCESSORS_T (
   apaSurrogateKey bigint not null,
   userSurrogateKey bigint not null,
   accessors_index_col integer not null,
   primary key (apaSurrogateKey, accessors_index_col)
);
create table MFR_AP_MODERATORS_T (
   apmSurrogateKey bigint not null,
   userSurrogateKey bigint not null,
   moderators_index_col integer not null,
   primary key (apmSurrogateKey, moderators_index_col)
);
create table MFR_TOPIC_T (
   ID bigint generated by default as identity (start with 1),
   TOPIC_DTYPE varchar(2) not null,
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   DEFAULTASSIGNNAME varchar(255),
   TITLE varchar(255) not null,
   SHORT_DESCRIPTION varchar(255),
   EXTENDED_DESCRIPTION longvarchar,
   MUTABLE bit not null,
   SORT_INDEX integer not null,
   TYPE_UUID varchar(36) not null,
   of_surrogateKey bigint,
   pf_surrogateKey bigint,
   USER_ID varchar(255),
   CONTEXT_ID varchar(36),
   pt_surrogateKey bigint,
   LOCKED bit,
   DRAFT bit,
   CONFIDENTIAL_RESPONSES bit,
   MUST_RESPOND_BEFORE_READING bit,
   HOUR_BEFORE_RESPONSES_VISIBLE integer,
   MODERATED bit,
   GRADEBOOK varchar(255),
   GRADEBOOK_ASSIGNMENT varchar(255)
);
create table MFR_MESSAGE_PERMISSIONS_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   ROLE_C varchar(255) not null,
   READ_C bit not null,
   REVISE_ANY bit not null,
   REVISE_OWN bit not null,
   DELETE_ANY bit not null,
   DELETE_OWN bit not null,
   READ_DRAFTS bit not null,
   MARK_AS_READ bit not null,
   DEFAULT_VALUE bit not null,
   areaSurrogateKey bigint,
   forumSurrogateKey bigint,
   topicSurrogateKey bigint
);
create table MFR_PERMISSION_LEVEL_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(255) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(255) not null,
   NAME varchar(50) not null,
   TYPE_UUID varchar(36) not null,
   CHANGE_SETTINGS bit not null,
   DELETE_ANY bit not null,
   DELETE_OWN bit not null,
   MARK_AS_READ bit not null,
   MOVE_POSTING bit not null,
   NEW_FORUM bit not null,
   NEW_RESPONSE bit not null,
   NEW_RESPONSE_TO_RESPONSE bit not null,
   NEW_TOPIC bit not null,
   POST_TO_GRADEBOOK bit not null,
   X_READ bit not null,
   REVISE_ANY bit not null,
   REVISE_OWN bit not null,
   MODERATE_POSTINGS bit not null
);
create table MFR_AP_CONTRIBUTORS_T (
   apcSurrogateKey bigint not null,
   userSurrogateKey bigint not null,
   contributors_index_col integer not null,
   primary key (apcSurrogateKey, contributors_index_col)
);
create table MFR_MESSAGE_T (
   ID bigint generated by default as identity (start with 1),
   MESSAGE_DTYPE varchar(2) not null,
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   TITLE varchar(255) not null,
   BODY longvarchar,
   AUTHOR varchar(255) not null,
   HAS_ATTACHMENTS bit not null,
   GRADECOMMENT longvarchar,
   GRADEASSIGNMENTNAME varchar(255),
   LABEL varchar(255),
   IN_REPLY_TO bigint,
   GRADEBOOK varchar(255),
   GRADEBOOK_ASSIGNMENT varchar(255),
   TYPE_UUID varchar(36) not null,
   APPROVED bit not null,
   DRAFT bit not null,
   surrogateKey bigint,
   EXTERNAL_EMAIL bit,
   EXTERNAL_EMAIL_ADDRESS varchar(255),
   RECIPIENTS_AS_TEXT longvarchar
);
create table MFR_AREA_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   CONTEXT_ID varchar(255) not null,
   NAME varchar(255) not null,
   HIDDEN bit not null,
   TYPE_UUID varchar(36) not null,
   ENABLED bit not null,
   LOCKED bit not null
);
create table MFR_PVT_MSG_USR_T (
   messageSurrogateKey bigint not null,
   USER_ID varchar(255) not null,
   TYPE_UUID varchar(255) not null,
   CONTEXT_ID varchar(255) not null,
   READ_STATUS bit not null,
   user_index_col integer not null,
   primary key (messageSurrogateKey, user_index_col)
);
create table MFR_ATTACHMENT_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(255) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(255) not null,
   ATTACHMENT_ID varchar(255) not null,
   ATTACHMENT_URL varchar(255) not null,
   ATTACHMENT_NAME varchar(255) not null,
   ATTACHMENT_SIZE varchar(255) not null,
   ATTACHMENT_TYPE varchar(255) not null,
   m_surrogateKey bigint,
   of_surrogateKey bigint,
   pf_surrogateKey bigint,
   t_surrogateKey bigint,
   of_urrogateKey bigint
);
create table MFR_ACTOR_PERMISSIONS_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null
);
create table MFR_MEMBERSHIP_ITEM_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(255) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(255) not null,
   NAME varchar(255) not null,
   TYPE integer not null,
   PERMISSION_LEVEL_NAME varchar(255) not null,
   PERMISSION_LEVEL bigint,
   a_surrogateKey bigint,
   of_surrogateKey bigint,
   t_surrogateKey bigint,
   unique (PERMISSION_LEVEL)
);
create table MFR_CONTROL_PERMISSIONS_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   ROLE varchar(255) not null,
   NEW_FORUM bit not null,
   POST_TO_GRADEBOOK bit not null,
   NEW_TOPIC bit not null,
   NEW_RESPONSE bit not null,
   RESPONSE_TO_RESPONSE bit not null,
   MOVE_POSTINGS bit not null,
   CHANGE_SETTINGS bit not null,
   DEFAULT_VALUE bit not null,
   areaSurrogateKey bigint,
   forumSurrogateKey bigint,
   topicSurrogateKey bigint
);
create table MFR_PRIVATE_FORUM_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   TITLE varchar(255) not null,
   SHORT_DESCRIPTION varchar(255),
   EXTENDED_DESCRIPTION longvarchar,
   TYPE_UUID varchar(36) not null,
   SORT_INDEX integer not null,
   OWNER varchar(255) not null,
   AUTO_FORWARD bit,
   AUTO_FORWARD_EMAIL varchar(255),
   PREVIEW_PANE_ENABLED bit,
   surrogateKey bigint
);
create table MFR_OPEN_FORUM_T (
   ID bigint generated by default as identity (start with 1),
   FORUM_DTYPE varchar(2) not null,
   VERSION integer not null,
   UUID varchar(36) not null,
   CREATED timestamp not null,
   CREATED_BY varchar(36) not null,
   MODIFIED timestamp not null,
   MODIFIED_BY varchar(36) not null,
   DEFAULTASSIGNNAME varchar(255),
   TITLE varchar(255) not null,
   SHORT_DESCRIPTION varchar(255),
   EXTENDED_DESCRIPTION longvarchar,
   TYPE_UUID varchar(36) not null,
   SORT_INDEX integer not null,
   LOCKED bit not null,
   DRAFT bit,
   surrogateKey bigint,
   MODERATED bit
);
create table MFR_MESSAGE_FORUMS_USER_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   UUID varchar(36) not null,
   USER_ID varchar(255) not null,
   TYPE_UUID varchar(36) not null
);
create table MFR_DATE_RESTRICTIONS_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   VISIBLE timestamp not null,
   VISIBLE_POST_ON_SCHEDULE bit not null,
   POSTING_ALLOWED timestamp not null,
   PSTNG_ALLWD_PST_ON_SCHD bit not null,
   READ_ONLY timestamp not null,
   READ_ONLY_POST_ON_SCHEDULE bit not null,
   HIDDEN timestamp not null,
   HIDDEN_POST_ON_SCHEDULE bit not null
);
create index MFR_LABEL_PARENT_I2 on MFR_LABEL_T (dt_surrogateKey);
create index MFR_LABEL_PARENT_I1 on MFR_LABEL_T (df_surrogateKey);
alter table MFR_LABEL_T add constraint FKC6611543EA902104 foreign key (df_surrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_LABEL_T add constraint FKC661154344B127B6 foreign key (dt_surrogateKey) references MFR_TOPIC_T;
create index MFR_UNREAD_STATUS_I1 on MFR_UNREAD_STATUS_T (TOPIC_C, MESSAGE_C, USER_C, READ_C);
alter table MFR_AP_ACCESSORS_T add constraint FKC8532ED796792399 foreign key (apaSurrogateKey) references MFR_ACTOR_PERMISSIONS_T;
alter table MFR_AP_ACCESSORS_T add constraint FKC8532ED721BCC7D2 foreign key (userSurrogateKey) references MFR_MESSAGE_FORUMS_USER_T;
alter table MFR_AP_MODERATORS_T add constraint FK75B43C0D21BCC7D2 foreign key (userSurrogateKey) references MFR_MESSAGE_FORUMS_USER_T;
alter table MFR_AP_MODERATORS_T add constraint FK75B43C0DC49D71A5 foreign key (apmSurrogateKey) references MFR_ACTOR_PERMISSIONS_T;
create index MFR_TOPIC_PARENT_I1 on MFR_TOPIC_T (of_surrogateKey);
create index MRF_TOPIC_DTYPE_I on MFR_TOPIC_T (TOPIC_DTYPE);
create index MFR_TOPIC_PRI_PARENT_I on MFR_TOPIC_T (pt_surrogateKey);
create index MFR_PT_CONTEXT_I on MFR_TOPIC_T (CONTEXT_ID);
create index MFR_TOPIC_PARENT_I2 on MFR_TOPIC_T (pf_surrogateKey);
create index MFR_TOPIC_CREATED_I on MFR_TOPIC_T (CREATED);
alter table MFR_TOPIC_T add constraint FK863DC0BEC6FDB1CF foreign key (of_surrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_TOPIC_T add constraint FK863DC0BE7AFA22C2 foreign key (pt_surrogateKey) references MFR_TOPIC_T;
alter table MFR_TOPIC_T add constraint FK863DC0BE20D91C10 foreign key (pf_surrogateKey) references MFR_PRIVATE_FORUM_T;
create index MFR_MP_PARENT_FORUM_I on MFR_MESSAGE_PERMISSIONS_T (forumSurrogateKey);
create index MFR_MP_PARENT_AREA_I on MFR_MESSAGE_PERMISSIONS_T (areaSurrogateKey);
create index MFR_MP_PARENT_TOPIC_I on MFR_MESSAGE_PERMISSIONS_T (topicSurrogateKey);
alter table MFR_MESSAGE_PERMISSIONS_T add constraint FK750F9AFB17721828 foreign key (forumSurrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_MESSAGE_PERMISSIONS_T add constraint FK750F9AFB51C89994 foreign key (areaSurrogateKey) references MFR_AREA_T;
alter table MFR_MESSAGE_PERMISSIONS_T add constraint FK750F9AFBE581B336 foreign key (topicSurrogateKey) references MFR_TOPIC_T;
alter table MFR_AP_CONTRIBUTORS_T add constraint FKA221A1F7737F309B foreign key (apcSurrogateKey) references MFR_ACTOR_PERMISSIONS_T;
alter table MFR_AP_CONTRIBUTORS_T add constraint FKA221A1F721BCC7D2 foreign key (userSurrogateKey) references MFR_MESSAGE_FORUMS_USER_T;
create index MFR_MESSAGE_LABEL_I on MFR_MESSAGE_T (LABEL);
create index MFR_MESSAGE_HAS_ATTACHMENTS_I on MFR_MESSAGE_T (HAS_ATTACHMENTS);
create index MFR_MESSAGE_CREATED_I on MFR_MESSAGE_T (CREATED);
create index MFR_MESSAGE_AUTHOR_I on MFR_MESSAGE_T (AUTHOR);
create index MFR_MESSAGE_DTYPE_I on MFR_MESSAGE_T (MESSAGE_DTYPE);
create index MFR_MESSAGE_TITLE_I on MFR_MESSAGE_T (TITLE);
create index MFR_MESSAGE_PARENT_TOPIC_I on MFR_MESSAGE_T (surrogateKey);
alter table MFR_MESSAGE_T add constraint FK80C1A316FE0789EA foreign key (IN_REPLY_TO) references MFR_MESSAGE_T;
alter table MFR_MESSAGE_T add constraint FK80C1A3164FDCE067 foreign key (surrogateKey) references MFR_TOPIC_T;
create index MFR_AREA_CONTEXT_I on MFR_AREA_T (CONTEXT_ID);
create index MFR_AREA_TYPE_I on MFR_AREA_T (TYPE_UUID);
create index MFR_PVT_MSG_USR_I1 on MFR_PVT_MSG_USR_T (USER_ID, TYPE_UUID, CONTEXT_ID, READ_STATUS);
alter table MFR_PVT_MSG_USR_T add constraint FKC4DE0E14FA8620E foreign key (messageSurrogateKey) references MFR_MESSAGE_T;
create index MFR_ATTACHMENT_PARENT_I4 on MFR_ATTACHMENT_T (t_surrogateKey);
create index MFR_ATTACHMENT_PARENT_I on MFR_ATTACHMENT_T (m_surrogateKey);
create index MFR_ATTACHMENT_PARENT_I3 on MFR_ATTACHMENT_T (pf_surrogateKey);
create index MFR_ATTACHMENT_PARENT_I2 on MFR_ATTACHMENT_T (of_surrogateKey);
alter table MFR_ATTACHMENT_T add constraint FK7B2D5CDE2AFBA652 foreign key (t_surrogateKey) references MFR_TOPIC_T;
alter table MFR_ATTACHMENT_T add constraint FK7B2D5CDEC6FDB1CF foreign key (of_surrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_ATTACHMENT_T add constraint FK7B2D5CDE20D91C10 foreign key (pf_surrogateKey) references MFR_PRIVATE_FORUM_T;
alter table MFR_ATTACHMENT_T add constraint FK7B2D5CDEFDEB22F9 foreign key (m_surrogateKey) references MFR_MESSAGE_T;
alter table MFR_ATTACHMENT_T add constraint FK7B2D5CDEAD5AF852 foreign key (of_urrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_MEMBERSHIP_ITEM_T add constraint FKE03761CB6785AF85 foreign key (a_surrogateKey) references MFR_AREA_T;
alter table MFR_MEMBERSHIP_ITEM_T add constraint FKE03761CBC6FDB1CF foreign key (of_surrogateKey) references MFR_OPEN_FORUM_T;
alter table MFR_MEMBERSHIP_ITEM_T add constraint FKE03761CB2AFBA652 foreign key (t_surrogateKey) references MFR_TOPIC_T;
alter table MFR_MEMBERSHIP_ITEM_T add constraint FKE03761CB925CE0F4 foreign key (PERMISSION_LEVEL) references MFR_PERMISSION_LEVEL_T;
create index MFR_CP_PARENT_FORUM_I on MFR_CONTROL_PERMISSIONS_T (forumSurrogateKey);
create index MFR_CP_PARENT_TOPIC_I on MFR_CONTROL_PERMISSIONS_T (topicSurrogateKey);
create index MFR_CP_PARENT_AREA_I on MFR_CONTROL_PERMISSIONS_T (areaSurrogateKey);
alter table MFR_CONTROL_PERMISSIONS_T add constraint FKA07CF1D1E581B336 foreign key (topicSurrogateKey) references MFR_TOPIC_T;
alter table MFR_CONTROL_PERMISSIONS_T add constraint FKA07CF1D151C89994 foreign key (areaSurrogateKey) references MFR_AREA_T;
alter table MFR_CONTROL_PERMISSIONS_T add constraint FKA07CF1D117721828 foreign key (forumSurrogateKey) references MFR_OPEN_FORUM_T;
create index MFR_PRIVATE_FORUM_CREATED_I on MFR_PRIVATE_FORUM_T (CREATED);
create index MFR_PRIVATE_FORUM_OWNER_I on MFR_PRIVATE_FORUM_T (OWNER);
create index MFR_PF_PARENT_BASEFORUM_I on MFR_PRIVATE_FORUM_T (surrogateKey);
alter table MFR_PRIVATE_FORUM_T add constraint FKA9EE57544FDCE067 foreign key (surrogateKey) references MFR_AREA_T;
create index MFR_OPEN_FORUM_DTYPE_I on MFR_OPEN_FORUM_T (FORUM_DTYPE);
create index MFR_OPEN_FORUM_TYPE_I on MFR_OPEN_FORUM_T (TYPE_UUID);
create index MFR_OF_PARENT_BASEFORUM_I on MFR_OPEN_FORUM_T (surrogateKey);
alter table MFR_OPEN_FORUM_T add constraint FKC17608474FDCE067 foreign key (surrogateKey) references MFR_AREA_T;
