svn rm alias/alias-api/api/
svn rm alias/alias-impl/impl/
svn rm alias/alias-impl/pack/
svn rm authz/authz-api/api/
svn rm authz/authz-impl/impl/
svn rm authz/authz-impl/integration-test/
svn rm authz/authz-impl/pack/
svn rm cluster/cluster-api/api/
svn rm cluster/cluster-impl/impl/
svn rm cluster/cluster-impl/pack/
svn rm component/component-api/api/
svn rm component/component-api/component/
svn rm component/component-impl/impl/
svn rm component/component-impl/integration-test/
svn rm component/component-impl/pack/
svn rm component/component-shared-deploy/
svn rm content/content-api/api/
svn rm content/content-impl/hbm/
svn rm content/content-impl/impl/
svn rm content/content-impl/pack/
svn rm content/content-impl-jcr/impl/
svn rm content/content-impl-jcr/pack/
svn rm content/content-jcr-migration-api/
svn rm content/content-jcr-migration-impl/
svn rm content/content-test/
svn rm content/content-util/util/
svn rm content/contentmultiplex-impl/impl/
svn rm db/db-api/api/
svn rm db/db-impl/ext/
svn rm db/db-impl/impl/
svn rm db/db-impl/pack/
svn rm db/db-shared-deploy/
svn rm db/db-util/conversion/
svn rm db/db-util/storage/
svn rm email/email-api/api/
svn rm email/email-impl/impl/
svn rm email/email-impl/pack/
svn rm email/email-shared-deploy/
svn rm entity/entity-api/api/
svn rm entity/entity-impl/impl/
svn rm entity/entity-impl/pack/
svn rm entity/entity-util/util/
svn rm event/event-api/api/
svn rm event/event-impl/impl/
svn rm event/event-impl/pack/
svn rm event/event-shared-deploy/
svn rm event/event-util/util/
svn rm jcr/jackrabbit-impl/impl/
svn rm jcr/jackrabbit-impl/pack/
svn rm jcr/jackrabbit-impl/
svn rm jcr/jcr-api/api/
svn rm jcr/jcr-api/
svn rm jcr/jcr-api/shared-deploy/
svn rm jcr/jcr-support/impl/
svn rm jcr/jcr-support/pack/
svn rm jcr/jcr-support/
svn rm jcr/jcr-util/
svn rm memory/memory-api/api/
svn rm memory/memory-impl/impl/
svn rm memory/memory-impl/pack/
svn rm site/site-api/api/
svn rm site/site-impl/impl/
svn rm site/site-impl/pack/
svn rm tool/tool-api/api/
svn rm tool/tool-impl/impl/
svn rm tool/tool-impl/pack/
svn rm tool/tool-shared-deploy/
svn rm tool/tool-util/servlet/
svn rm tool/tool-util/util/
svn rm user/user-api/api/
svn rm user/user-impl/impl/
svn rm user/user-impl/integration-test/
svn rm user/user-impl/pack/
svn rm user/user-util/util/
svn rm util/util-api/api/
svn rm util/util-api/hbm/
svn rm util/util-common-deploy/
svn rm util/util-impl/impl/
svn rm util/util-impl/log/
svn rm util/util-impl/pack/
svn rm util/util-shared-deploy/
svn rm util/util-util/util/
