-- Most automatic database initialization will be taken care of automatically
-- by Hibernate's SchemaUpdate tool, triggered by the hibernate.hbm2ddl.auto
-- property in vanilla Hibernate applications and by the auto.ddl property
-- in the Sakai framework.
--
-- Not all necessary elements might be created by SchemaUpdate, however.
-- Notably, in versions of Hibernate through at least 3.1.3, no explicit
-- index definitions in the mapping file will be honored except during a
-- full SchemaExport.
--
-- This file creates schema in reverse order of when they were added to
-- SiteStats out-of-the-box SQL, to increase the chances that the script
-- will have useful results as an upgrader as well as an initializer.
ALTER TABLE SST_EVENTS  DROP INDEX SITE_ID_IX, ADD INDEX SST_EVENTS_SITE_ID_IX USING BTREE(SITE_ID);
ALTER TABLE SST_EVENTS  DROP INDEX USER_ID_IX, ADD INDEX SST_EVENTS_USER_ID_IX USING BTREE(USER_ID);
ALTER TABLE SST_EVENTS  DROP INDEX EVENT_ID_IX, ADD INDEX SST_EVENTS_EVENT_ID_IX USING BTREE(EVENT_ID);
ALTER TABLE SST_EVENTS  DROP INDEX DATE_ID_IX, ADD INDEX SST_EVENTS_DATE_ID_IX USING BTREE(EVENT_DATE);

ALTER TABLE SST_RESOURCES  DROP INDEX SITE_ID_IX, ADD INDEX SST_RESOURCES_SITE_ID_IX USING BTREE(SITE_ID);
ALTER TABLE SST_RESOURCES  DROP INDEX USER_ID_IX, ADD INDEX SST_RESOURCES_USER_ID_IX USING BTREE(USER_ID);
ALTER TABLE SST_RESOURCES  DROP INDEX RES_ACT_IDX, ADD INDEX SST_RESOURCES_RES_ACT_IDX USING BTREE(RESOURCE_ACTION);
ALTER TABLE SST_RESOURCES  DROP INDEX DATE_ID_IX, ADD INDEX SST_RESOURCES_DATE_ID_IX USING BTREE(RESOURCE_DATE);

ALTER TABLE SST_SITEACTIVITY  DROP INDEX SITE_ID_IX, ADD INDEX SST_SITEACTIVITY_SITE_ID_IX USING BTREE(SITE_ID);
ALTER TABLE SST_SITEACTIVITY  DROP INDEX EVENT_ID_IX, ADD INDEX SST_SITEACTIVITY_EVENT_ID_IX USING BTREE(EVENT_ID);
ALTER TABLE SST_SITEACTIVITY  DROP INDEX DATE_ACT_IX, ADD INDEX SST_SITEACTIVITY_DATE_ID_IX USING BTREE(ACTIVITY_DATE);

ALTER TABLE SST_SITEVISITS  DROP INDEX SITE_ID_IX, ADD INDEX SST_SITEVISITS_SITE_ID_IX USING BTREE(SITE_ID);
ALTER TABLE SST_SITEVISITS  DROP INDEX DATE_ID_IX, ADD INDEX SST_SITEVISITS_DATE_ID_IX USING BTREE(VISITS_DATE);