alter index lesson_builder_log_index rename to lb_log_index;
alter index lesson_builder_comments_uuid rename to lb_comments_uuid;
alter index lesson_builder_comments_author rename to lb_comments_author;
alter index lesson_builder_log_index3 rename to lb_log_index3;
alter index lesson_builder_log_index2 rename to lb_log_index2;
alter index lesson_builder_groups_itemid rename to lb_groups_itemid;
alter index lesson_builder_pages_toolid rename to lb_pages_toolid;
alter index lesson_builder_items_pageid rename to lb_items_pageid;
alter index lesson_builder_items_sakaiid rename to lb_items_sakaiid;
