var data = {"entityPrefix": "signupEvent", "signupEvent_collection": [
{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1233673200000,
  "description": "<p>Welcome to the class!<\/p>\r\n<p>&nbsp;<\/p>\r\n<p>peter<\/p>",
  "endTime": 1233676800000,
  "eventId": 2,
  "id": "2",
  "location": "Earle Hall, Rm 101",
  "maxNumberOfAttendees": 0,
  "meetingType": "group",
  "noOfTimeSlots": 0,
  "organizerName": "tester-2 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/2",
  "signupBegins": 1233154800000,
  "signupDeadline": 1233673200000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1233673200000,
  "title": "Welcome Session cp",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/2",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/2",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/2",
  "entityId": "2",
  "entityTitle": "Welcome Session cp"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234202400000,
  "description": "<p>test<\/p>",
  "endTime": 1234206000000,
  "eventId": 3,
  "id": "3",
  "location": "12345",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 3,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/3",
  "signupBegins": 1233684000000,
  "signupDeadline": 1234202400000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234202400000,
  "title": "weekly tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/3",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/3",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/3",
  "entityId": "3",
  "entityTitle": "weekly tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234548000000,
  "description": "<p>xvxvx<\/p>",
  "endTime": 1234551600000,
  "eventId": 8,
  "id": "8",
  "location": "xvxv",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-2 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/8",
  "signupBegins": 1234029600000,
  "signupDeadline": 1234548000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234548000000,
  "title": "cvx",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/8",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/8",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/8",
  "entityId": "8",
  "entityTitle": "cvx"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234551600000,
  "description": "<p>xcvxv<\/p>",
  "endTime": 1234555200000,
  "eventId": 10,
  "id": "10",
  "location": "xcvxv",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/10",
  "signupBegins": 1234033200000,
  "signupDeadline": 1234551600000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234551600000,
  "title": "xcvxv",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/10",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/10",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/10",
  "entityId": "10",
  "entityTitle": "xcvxv"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234720800000,
  "description": "<p>sfsfsf<\/p>",
  "endTime": 1234724400000,
  "eventId": 6,
  "id": "6",
  "location": "sfsf",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-19 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/6",
  "signupBegins": 1234202400000,
  "signupDeadline": 1234720800000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234720800000,
  "title": "tester-19",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/6",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/6",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/6",
  "entityId": "6",
  "entityTitle": "tester-19"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234807200000,
  "description": "<p>test<\/p>",
  "endTime": 1234810800000,
  "eventId": 4,
  "id": "4",
  "location": "12345",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 3,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/4",
  "signupBegins": 1233943200000,
  "signupDeadline": 1234807200000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234807200000,
  "title": "weekly tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/4",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/4",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/4",
  "entityId": "4",
  "entityTitle": "weekly tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234807200000,
  "description": "<p>test<\/p>",
  "endTime": 1234810800000,
  "eventId": 7,
  "id": "7",
  "location": "12345",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/7",
  "signupBegins": 1233943200000,
  "signupDeadline": 1234807200000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234807200000,
  "title": "weekly tutorial site",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/7",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/7",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/7",
  "entityId": "7",
  "entityTitle": "weekly tutorial site"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1234893600000,
  "description": "<p>xvxvx<\/p>",
  "endTime": 1234897200000,
  "eventId": 9,
  "id": "9",
  "location": "xvxv",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-2 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/9",
  "signupBegins": 1234375200000,
  "signupDeadline": 1234893600000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1234893600000,
  "title": "cvx cp",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/9",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/9",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/9",
  "entityId": "9",
  "entityTitle": "cvx cp"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1235412000000,
  "description": "<p>test<\/p>",
  "endTime": 1235415600000,
  "eventId": 5,
  "id": "5",
  "location": "12345",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 3,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/5",
  "signupBegins": 1234548000000,
  "signupDeadline": 1235412000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1235412000000,
  "title": "weekly tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/5",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/5",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/5",
  "entityId": "5",
  "entityTitle": "weekly tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1237125600000,
  "description": "<p>Welcome to the class!<\/p>\r\n<p>&nbsp;<\/p>\r\n<p>peter<\/p>",
  "endTime": 1237129200000,
  "eventId": 11,
  "id": "11",
  "location": "Earle Hall, Rm 101",
  "maxNumberOfAttendees": 0,
  "meetingType": "group",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/11",
  "signupBegins": 1236261600000,
  "signupDeadline": 1237125600000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1237125600000,
  "title": "Welcome Session 2",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/11",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/11",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/11",
  "entityId": "11",
  "entityTitle": "Welcome Session 2"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1237140000000,
  "description": "<p>please join!<\/p>",
  "endTime": 1237143600000,
  "eventId": 12,
  "id": "12",
  "location": "32123",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/12",
  "signupBegins": 1236621600000,
  "signupDeadline": 1237140000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1237140000000,
  "title": "Math Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/12",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/12",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/12",
  "entityId": "12",
  "entityTitle": "Math Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Closed",
  "date": 1237554000000,
  "description": "<p>please join!<\/p>",
  "endTime": 1237557600000,
  "eventId": 15,
  "id": "15",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/15",
  "signupBegins": 1235826000000,
  "signupDeadline": 1237554000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1237554000000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/15",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": true,
  "passedDeadline": true,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/15",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/15",
  "entityId": "15",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Sign-up Not Req",
  "date": 1237726800000,
  "description": "<p>Welcome session<\/p>",
  "endTime": 1237730400000,
  "eventId": 13,
  "id": "13",
  "location": "43214",
  "maxNumberOfAttendees": 0,
  "meetingType": "announcement",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/13",
  "signupBegins": 1236690000000,
  "signupDeadline": 1237726800000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1237726800000,
  "title": "Annoncement",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/13",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/13",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/13",
  "entityId": "13",
  "entityTitle": "Annoncement"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available",
  "date": 1238004000000,
  "description": "<p>please join!<\/p>",
  "endTime": 1238007600000,
  "eventId": 14,
  "id": "14",
  "location": "32123",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": null,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/14",
  "signupBegins": 1237053600000,
  "signupDeadline": 1238004000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1238004000000,
  "title": "Math Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/14",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/14",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/14",
  "entityId": "14",
  "entityTitle": "Math Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "<font color='red'>Signed up<\/font>",
  "date": 1238158800000,
  "description": "<p>please join!<\/p>",
  "endTime": 1238162400000,
  "eventId": 16,
  "id": "16",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/16",
  "signupBegins": 1236430800000,
  "signupDeadline": 1238158800000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1238158800000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/16",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": true,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/16",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/16",
  "entityId": "16",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available",
  "date": 1238763600000,
  "description": "<p>please join!<\/p>",
  "endTime": 1238767200000,
  "eventId": 17,
  "id": "17",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/17",
  "signupBegins": 1237032000000,
  "signupDeadline": 1238763600000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1238763600000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/17",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": true,
  "entityReference": "\/signupEvent\/17",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/17",
  "entityId": "17",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available on 3\/21\/09",
  "date": 1239368400000,
  "description": "<p>please join!<\/p>",
  "endTime": 1239372000000,
  "eventId": 18,
  "id": "18",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/18",
  "signupBegins": 1237636800000,
  "signupDeadline": 1239368400000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1239368400000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/18",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/18",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/18",
  "entityId": "18",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available on 3\/28\/09",
  "date": 1239973200000,
  "description": "<p>please join!<\/p>",
  "endTime": 1239976800000,
  "eventId": 19,
  "id": "19",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/19",
  "signupBegins": 1238241600000,
  "signupDeadline": 1239973200000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1239973200000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/19",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/19",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/19",
  "entityId": "19",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available on 4\/4\/09",
  "date": 1240578000000,
  "description": "<p>please join!<\/p>",
  "endTime": 1240581600000,
  "eventId": 20,
  "id": "20",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/20",
  "signupBegins": 1238846400000,
  "signupDeadline": 1240578000000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1240578000000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/20",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/20",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/20",
  "entityId": "20",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available on 4\/11\/09",
  "date": 1241182800000,
  "description": "<p>please join!<\/p>",
  "endTime": 1241186400000,
  "eventId": 21,
  "id": "21",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/21",
  "signupBegins": 1239451200000,
  "signupDeadline": 1241182800000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1241182800000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/21",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/21",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/21",
  "entityId": "21",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "Available on 4\/18\/09",
  "date": 1241787600000,
  "description": "<p>please join!<\/p>",
  "endTime": 1241791200000,
  "eventId": 22,
  "id": "22",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/22",
  "signupBegins": 1240056000000,
  "signupDeadline": 1241787600000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1241787600000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/22",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": false,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/22",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/22",
  "entityId": "22",
  "entityTitle": "English Tutorial"
},{
  "allocToTSid": null,
  "allowedUserActionTypes": null,
  "availableStatus": "<font color='red'>Signed up<\/font>",
  "date": 1242392400000,
  "description": "<p>please join!<\/p>",
  "endTime": 1242396000000,
  "eventId": 23,
  "id": "23",
  "location": "Earle Hall",
  "maxNumberOfAttendees": 0,
  "meetingType": "individual",
  "noOfTimeSlots": 0,
  "organizerName": "tester-1 local",
  "permission": {
    "attend": true,
    "delete": true,
    "update": true
  },
  "properties": null,
  "recurrenceId": 15,
  "reference": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/\/23",
  "signupBegins": 1240660800000,
  "signupDeadline": 1242392400000,
  "signupSiteItems": null,
  "signupTimeSlotItems": null,
  "siteId": "c8f0e8a4-31fd-4525-ac5e-6788d612347c",
  "startTime": 1242392400000,
  "title": "English Tutorial",
  "url": "http:\/\/academicapps1.yu.yale.edu:8080\/access\/signupEvent\/23",
  "userActionType": null,
  "userActionWarningMsg": null,
  "currentUserSignedUp": true,
  "meetingCrossDays": false,
  "meetingExpired": false,
  "passedDeadline": false,
  "startToSignUp": false,
  "entityReference": "\/signupEvent\/23",
  "entityURL": "http:\/\/academicapps1.yu.yale.edu:8080\/direct\/signupEvent\/23",
  "entityId": "23",
  "entityTitle": "English Tutorial"
}
]};