type printableHeader.html > printReadmeRTE.html
type toc.html >> printReadmeRTE.html
type rteIntroduction.html >> printReadmeRTE.html
type rteInstallation.html >> printReadmeRTE.html
type knownIssuesRTE.html >> printReadmeRTE.html
type revisionsToRTE.html >> printReadmeRTE.html
type runSampleRTE.html >> printReadmeRTE.html
type rteServerComponent.html >> printReadmeRTE.html
type rteClientComponentJava.html >> printReadmeRTE.html
type rteClientComponentWeb.html >> printReadmeRTE.html
type buildingTheRTE.html >> printReadmeRTE.html
type implementationDecisions.html >> printReadmeRTE.html
type thirdPartyComponents.html >> printReadmeRTE.html
type licenseCopyright.html >> printReadmeRTE.html