drop table if exists GB_LETTERGRADE_PERCENT_MAPPING;
drop table if exists GB_LETTERGRADE_MAPPING;
create table GB_LETTERGRADE_MAPPING (id bigint not null, value double precision, grade varchar(255) not null, primary key (id, grade));
create table GB_LETTERGRADE_PERCENT_MAPPING (ID bigint not null auto_increment, VERSION integer not null, MAPPING_TYPE integer not null, GRADEBOOK_ID bigint, primary key (ID), unique (MAPPING_TYPE, GRADEBOOK_ID));
alter table GB_LETTERGRADE_MAPPING add index FKC8CDDC5CE7F3A761 (id), add constraint FKC8CDDC5CE7F3A761 foreign key (id) references GB_LETTERGRADE_PERCENT_MAPPING (ID);

insert into GB_LETTERGRADE_PERCENT_MAPPING values (null,  0, 1, null);
insert into GB_LETTERGRADE_MAPPING values (1, 0.98, 'a+');
insert into GB_LETTERGRADE_MAPPING values (1, 0.95, 'a');
insert into GB_LETTERGRADE_MAPPING values (1, 0.90, 'a-');
insert into GB_LETTERGRADE_MAPPING values (1, 0.88, 'b+');
insert into GB_LETTERGRADE_MAPPING values (1, 0.85, 'b');
insert into GB_LETTERGRADE_MAPPING values (1, 0.80, 'b-');
insert into GB_LETTERGRADE_MAPPING values (1, 0.78, 'c+');
insert into GB_LETTERGRADE_MAPPING values (1, 0.75, 'c');
insert into GB_LETTERGRADE_MAPPING values (1, 0.70, 'c-');
insert into GB_LETTERGRADE_MAPPING values (1, 0.68, 'd+');
insert into GB_LETTERGRADE_MAPPING values (1, 0.65, 'd');
insert into GB_LETTERGRADE_MAPPING values (1, 0.60, 'd-');
insert into GB_LETTERGRADE_MAPPING values (1, 0.0, 'f');