drop table if exists GB_LETTERGRADE_PERCENT_MAPPING;
drop table if exists GB_LETTERGRADE_MAPPING;
create table GB_LETTERGRADE_MAPPING (id bigint not null, value double precision, grade varchar(255) not null, primary key (id, grade));
create table GB_LETTERGRADE_PERCENT_MAPPING (ID bigint not null auto_increment, VERSION integer not null, MAPPING_TYPE integer not null, GRADEBOOK_ID bigint, primary key (ID), unique (MAPPING_TYPE, GRADEBOOK_ID));
alter table GB_LETTERGRADE_MAPPING add index FKC8CDDC5CE7F3A761 (id), add constraint FKC8CDDC5CE7F3A761 foreign key (id) references GB_LETTERGRADE_PERCENT_MAPPING (ID);

insert into GB_LETTERGRADE_PERCENT_MAPPING values (null,  0, 1, null);
insert into GB_LETTERGRADE_MAPPING values (1, 98.0, 'A+');
insert into GB_LETTERGRADE_MAPPING values (1, 95.0, 'A');
insert into GB_LETTERGRADE_MAPPING values (1, 90.0, 'A-');
insert into GB_LETTERGRADE_MAPPING values (1, 88.0, 'B+');
insert into GB_LETTERGRADE_MAPPING values (1, 85.0, 'B');
insert into GB_LETTERGRADE_MAPPING values (1, 80.0, 'B-');
insert into GB_LETTERGRADE_MAPPING values (1, 78.0, 'C+');
insert into GB_LETTERGRADE_MAPPING values (1, 75.0, 'C');
insert into GB_LETTERGRADE_MAPPING values (1, 70.0, 'C-');
insert into GB_LETTERGRADE_MAPPING values (1, 68.0, 'D+');
insert into GB_LETTERGRADE_MAPPING values (1, 65.0, 'D');
insert into GB_LETTERGRADE_MAPPING values (1, 60.0, 'D-');
insert into GB_LETTERGRADE_MAPPING values (1, 0.0, 'F');