ALTER TABLE HIERARCHY_NODE ADD COLUMN HIERARCHYID VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISROOTNODE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE HIERARCHY_NODE ADD COLUMN OWNERID VARCHAR(99);
ALTER TABLE HIERARCHY_NODE ADD COLUMN TITLE VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN DESCRIPTION LONGVARCHAR;
ALTER TABLE HIERARCHY_NODE ADD COLUMN PERMTOKEN VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISDISABLED BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE HIERARCHY_NODE SET HIERARCHYID = (SELECT HIERARCHYID FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), ISROOTNODE = (SELECT ISROOTNODE FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), OWNERID = (SELECT OWNERID FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), TITLE = (SELECT TITLE FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), DESCRIPTION = (SELECT DESCRIPTION FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), PERMTOKEN = (SELECT PERMTOKEN FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), ISDISABLED = COALESCE((SELECT ISDISABLED FROM HIERARCHY_NODE_META WHERE ID = HIERARCHY_NODE.ID), FALSE);
DROP TABLE HIERARCHY_NODE_META;

-- JPA @ManyToMany join table replacing encoded-string parent/child columns
CREATE TABLE IF NOT EXISTS HIERARCHY_NODE_PARENTS (
    NODE_ID        BIGINT NOT NULL,
    PARENT_NODE_ID BIGINT NOT NULL,
    CONSTRAINT FK_HNP_NODE   FOREIGN KEY (NODE_ID)        REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT FK_HNP_PARENT FOREIGN KEY (PARENT_NODE_ID) REFERENCES HIERARCHY_NODE(ID),
    PRIMARY KEY (NODE_ID, PARENT_NODE_ID)
);
