ALTER TABLE HIERARCHY_NODE ADD COLUMN HIERARCHYID VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISROOTNODE TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE HIERARCHY_NODE ADD COLUMN OWNERID VARCHAR(99);
ALTER TABLE HIERARCHY_NODE ADD COLUMN TITLE VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN DESCRIPTION LONGTEXT;
ALTER TABLE HIERARCHY_NODE ADD COLUMN PERMTOKEN VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISDISABLED TINYINT(1) NOT NULL DEFAULT 0;
UPDATE HIERARCHY_NODE n JOIN HIERARCHY_NODE_META m ON n.ID = m.ID SET n.HIERARCHYID = m.HIERARCHYID, n.ISROOTNODE = m.ISROOTNODE, n.OWNERID = m.OWNERID, n.TITLE = m.TITLE, n.DESCRIPTION = m.DESCRIPTION, n.PERMTOKEN = m.PERMTOKEN, n.ISDISABLED = COALESCE(m.ISDISABLED, 0);
DROP TABLE HIERARCHY_NODE_META;

-- JPA @ManyToMany join table replacing encoded-string parent/child columns
CREATE TABLE IF NOT EXISTS HIERARCHY_NODE_PARENTS (
    NODE_ID        BIGINT NOT NULL,
    PARENT_NODE_ID BIGINT NOT NULL,
    CONSTRAINT FK_HNP_NODE   FOREIGN KEY (NODE_ID)        REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT FK_HNP_PARENT FOREIGN KEY (PARENT_NODE_ID) REFERENCES HIERARCHY_NODE(ID),
    PRIMARY KEY (NODE_ID, PARENT_NODE_ID)
);
