ALTER TABLE HIERARCHY_NODE ADD COLUMN HIERARCHYID VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISROOTNODE TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE HIERARCHY_NODE ADD COLUMN OWNERID VARCHAR(99);
ALTER TABLE HIERARCHY_NODE ADD COLUMN TITLE VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN DESCRIPTION LONGTEXT;
ALTER TABLE HIERARCHY_NODE ADD COLUMN PERMTOKEN VARCHAR(255);
ALTER TABLE HIERARCHY_NODE ADD COLUMN ISDISABLED TINYINT(1) NOT NULL DEFAULT 0;
UPDATE HIERARCHY_NODE n JOIN HIERARCHY_NODE_META m ON n.ID = m.ID SET n.HIERARCHYID = m.HIERARCHYID, n.ISROOTNODE = m.ISROOTNODE, n.OWNERID = m.OWNERID, n.TITLE = m.TITLE, n.DESCRIPTION = m.DESCRIPTION, n.PERMTOKEN = m.PERMTOKEN, n.ISDISABLED = COALESCE(m.ISDISABLED, 0);
DROP TABLE HIERARCHY_NODE_META;

CREATE INDEX IF NOT EXISTS IDX_HN_HIERARCHYID ON HIERARCHY_NODE (HIERARCHYID);

-- JPA @ManyToMany join table replacing encoded-string parent/child columns
CREATE TABLE IF NOT EXISTS HIERARCHY_NODE_PARENTS (
    NODE_ID        BIGINT NOT NULL,
    PARENT_NODE_ID BIGINT NOT NULL,
    CONSTRAINT FK_HNP_NODE   FOREIGN KEY (NODE_ID)        REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT FK_HNP_PARENT FOREIGN KEY (PARENT_NODE_ID) REFERENCES HIERARCHY_NODE(ID),
    PRIMARY KEY (NODE_ID, PARENT_NODE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_HNP_PARENT_NODE_ID ON HIERARCHY_NODE_PARENTS (PARENT_NODE_ID);

-- Migrate encoded parent IDs to HIERARCHY_NODE_PARENTS (upgrade from pre-JPA schema)
DROP PROCEDURE IF EXISTS hierarchy_migrate_parents;
CREATE PROCEDURE hierarchy_migrate_parents()
BEGIN
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME   = 'HIERARCHY_NODE'
          AND COLUMN_NAME  = 'DIRECTPARENTIDS'
    ) THEN
        INSERT IGNORE INTO HIERARCHY_NODE_PARENTS (NODE_ID, PARENT_NODE_ID)
        WITH RECURSIVE split(node_id, rest) AS (
            SELECT ID, CONCAT(TRIM(BOTH ':' FROM DIRECTPARENTIDS), ':')
            FROM   HIERARCHY_NODE
            WHERE  DIRECTPARENTIDS IS NOT NULL
              AND  TRIM(BOTH ':' FROM DIRECTPARENTIDS) != ''
            UNION ALL
            SELECT node_id, SUBSTRING(rest, LOCATE(':', rest) + 1)
            FROM   split
            WHERE  LOCATE(':', rest) > 0
        )
        SELECT node_id, CAST(SUBSTRING_INDEX(rest, ':', 1) AS UNSIGNED)
        FROM   split
        WHERE  LOCATE(':', rest) > 0
          AND  SUBSTRING_INDEX(rest, ':', 1) REGEXP '^[0-9]+$';

        ALTER TABLE HIERARCHY_NODE DROP COLUMN DIRECTPARENTIDS;
        ALTER TABLE HIERARCHY_NODE DROP COLUMN PARENTIDS;
        ALTER TABLE HIERARCHY_NODE DROP COLUMN DIRECTCHILDIDS;
        ALTER TABLE HIERARCHY_NODE DROP COLUMN CHILDIDS;
    END IF;
END;
CALL hierarchy_migrate_parents();
DROP PROCEDURE IF EXISTS hierarchy_migrate_parents;
