ALTER TABLE HIERARCHY_NODE ADD HIERARCHYID VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD ISROOTNODE NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HIERARCHY_NODE ADD OWNERID VARCHAR2(99);
ALTER TABLE HIERARCHY_NODE ADD TITLE VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD DESCRIPTION CLOB;
ALTER TABLE HIERARCHY_NODE ADD PERMTOKEN VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD ISDISABLED NUMBER(1,0) DEFAULT 0 NOT NULL;
UPDATE HIERARCHY_NODE n SET (n.HIERARCHYID, n.ISROOTNODE, n.OWNERID, n.TITLE, n.DESCRIPTION, n.PERMTOKEN, n.ISDISABLED) = (SELECT m.HIERARCHYID, m.ISROOTNODE, m.OWNERID, m.TITLE, m.DESCRIPTION, m.PERMTOKEN, NVL(m.ISDISABLED, 0) FROM HIERARCHY_NODE_META m WHERE m.ID = n.ID) WHERE EXISTS (SELECT 1 FROM HIERARCHY_NODE_META m WHERE m.ID = n.ID);
DROP TABLE HIERARCHY_NODE_META;

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_HN_HIERARCHYID ON HIERARCHY_NODE (HIERARCHYID)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- JPA @ManyToMany join table replacing encoded-string parent/child columns
CREATE TABLE HIERARCHY_NODE_PARENTS (
    NODE_ID        NUMBER(19,0) NOT NULL,
    PARENT_NODE_ID NUMBER(19,0) NOT NULL,
    CONSTRAINT FK_HNP_NODE   FOREIGN KEY (NODE_ID)        REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT FK_HNP_PARENT FOREIGN KEY (PARENT_NODE_ID) REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT PK_HNP        PRIMARY KEY (NODE_ID, PARENT_NODE_ID)
);

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_HNP_PARENT_NODE_ID ON HIERARCHY_NODE_PARENTS (PARENT_NODE_ID)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Migrate encoded parent IDs to HIERARCHY_NODE_PARENTS (upgrade from pre-JPA schema)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM   USER_TAB_COLUMNS
    WHERE  TABLE_NAME  = 'HIERARCHY_NODE'
      AND  COLUMN_NAME = 'DIRECTPARENTIDS';

    IF v_count > 0 THEN
        INSERT INTO HIERARCHY_NODE_PARENTS (NODE_ID, PARENT_NODE_ID)
        SELECT DISTINCT n.ID,
               TO_NUMBER(REGEXP_SUBSTR(n.DIRECTPARENTIDS, '\d+', 1, LEVEL))
        FROM   HIERARCHY_NODE n
        WHERE  n.DIRECTPARENTIDS IS NOT NULL
          AND  REGEXP_LIKE(n.DIRECTPARENTIDS, '\d+')
        CONNECT BY LEVEL <= REGEXP_COUNT(n.DIRECTPARENTIDS, '\d+')
            AND PRIOR n.ID        = n.ID
            AND PRIOR SYS_GUID() IS NOT NULL;

        EXECUTE IMMEDIATE 'ALTER TABLE HIERARCHY_NODE DROP COLUMN DIRECTPARENTIDS';
        EXECUTE IMMEDIATE 'ALTER TABLE HIERARCHY_NODE DROP COLUMN PARENTIDS';
        EXECUTE IMMEDIATE 'ALTER TABLE HIERARCHY_NODE DROP COLUMN DIRECTCHILDIDS';
        EXECUTE IMMEDIATE 'ALTER TABLE HIERARCHY_NODE DROP COLUMN CHILDIDS';
    END IF;
END;
/
