ALTER TABLE HIERARCHY_NODE ADD HIERARCHYID VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD ISROOTNODE NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE HIERARCHY_NODE ADD OWNERID VARCHAR2(99);
ALTER TABLE HIERARCHY_NODE ADD TITLE VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD DESCRIPTION CLOB;
ALTER TABLE HIERARCHY_NODE ADD PERMTOKEN VARCHAR2(255);
ALTER TABLE HIERARCHY_NODE ADD ISDISABLED NUMBER(1,0) DEFAULT 0 NOT NULL;
UPDATE HIERARCHY_NODE n SET (n.HIERARCHYID, n.ISROOTNODE, n.OWNERID, n.TITLE, n.DESCRIPTION, n.PERMTOKEN, n.ISDISABLED) = (SELECT m.HIERARCHYID, m.ISROOTNODE, m.OWNERID, m.TITLE, m.DESCRIPTION, m.PERMTOKEN, NVL(m.ISDISABLED, 0) FROM HIERARCHY_NODE_META m WHERE m.ID = n.ID) WHERE EXISTS (SELECT 1 FROM HIERARCHY_NODE_META m WHERE m.ID = n.ID);
DROP TABLE HIERARCHY_NODE_META;

-- JPA @ManyToMany join table replacing encoded-string parent/child columns
CREATE TABLE HIERARCHY_NODE_PARENTS (
    NODE_ID        NUMBER(19,0) NOT NULL,
    PARENT_NODE_ID NUMBER(19,0) NOT NULL,
    CONSTRAINT FK_HNP_NODE   FOREIGN KEY (NODE_ID)        REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT FK_HNP_PARENT FOREIGN KEY (PARENT_NODE_ID) REFERENCES HIERARCHY_NODE(ID),
    CONSTRAINT PK_HNP        PRIMARY KEY (NODE_ID, PARENT_NODE_ID)
);
