package org.sakaiproject.kernel.model;

/** Class _ContentResourceBodyBinary was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ContentResourceBodyBinary extends org.apache.cayenne.CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String RESOURCE_ID_PROPERTY = "resourceId";

    public static final String ID_PK_COLUMN = "ID";

    public void setBody(byte[] body) {
        writeProperty("body", body);
    }
    public byte[] getBody() {
        return (byte[])readProperty("body");
    }
    
    
    public void setResourceId(String resourceId) {
        writeProperty("resourceId", resourceId);
    }
    public String getResourceId() {
        return (String)readProperty("resourceId");
    }
    
    
}
