package org.sakaiproject.kernel.model;

/** Class _ContentResource was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ContentResource extends org.apache.cayenne.CayenneDataObject {

    public static final String BINARY_ENTITY_PROPERTY = "binaryEntity";
    public static final String CONTEXT_PROPERTY = "context";
    public static final String FILE_PATH_PROPERTY = "filePath";
    public static final String FILE_SIZE_PROPERTY = "fileSize";
    public static final String IN_COLLECTION_PROPERTY = "inCollection";
    public static final String RESOURCE_ID_PROPERTY = "resourceId";
    public static final String RESOURCE_TYPE_ID_PROPERTY = "resourceTypeId";
    public static final String RESOURCE_UUID_PROPERTY = "resourceUuid";
    public static final String XML_PROPERTY = "xml";

    public static final String ID_PK_COLUMN = "ID";

    public void setBinaryEntity(byte[] binaryEntity) {
        writeProperty("binaryEntity", binaryEntity);
    }
    public byte[] getBinaryEntity() {
        return (byte[])readProperty("binaryEntity");
    }
    
    
    public void setContext(String context) {
        writeProperty("context", context);
    }
    public String getContext() {
        return (String)readProperty("context");
    }
    
    
    public void setFilePath(String filePath) {
        writeProperty("filePath", filePath);
    }
    public String getFilePath() {
        return (String)readProperty("filePath");
    }
    
    
    public void setFileSize(Long fileSize) {
        writeProperty("fileSize", fileSize);
    }
    public Long getFileSize() {
        return (Long)readProperty("fileSize");
    }
    
    
    public void setInCollection(String inCollection) {
        writeProperty("inCollection", inCollection);
    }
    public String getInCollection() {
        return (String)readProperty("inCollection");
    }
    
    
    public void setResourceId(String resourceId) {
        writeProperty("resourceId", resourceId);
    }
    public String getResourceId() {
        return (String)readProperty("resourceId");
    }
    
    
    public void setResourceTypeId(String resourceTypeId) {
        writeProperty("resourceTypeId", resourceTypeId);
    }
    public String getResourceTypeId() {
        return (String)readProperty("resourceTypeId");
    }
    
    
    public void setResourceUuid(String resourceUuid) {
        writeProperty("resourceUuid", resourceUuid);
    }
    public String getResourceUuid() {
        return (String)readProperty("resourceUuid");
    }
    
    
    public void setXml(String xml) {
        writeProperty("xml", xml);
    }
    public String getXml() {
        return (String)readProperty("xml");
    }
    
    
}
