package org.sakaiproject.kernel.model;

import java.util.List;

/** Class _ContentCollection was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ContentCollection extends org.apache.cayenne.CayenneDataObject {

    public static final String BINARY_ENTITY_PROPERTY = "binaryEntity";
    public static final String COLLECTION_ID_PROPERTY = "collectionId";
    public static final String IN_COLLECTION_PROPERTY = "inCollection";
    public static final String XML_PROPERTY = "xml";
    public static final String PARENT_COLLECTION_PROPERTY = "parentCollection";

    public static final String ID_PK_COLUMN = "ID";

    public void setBinaryEntity(byte[] binaryEntity) {
        writeProperty("binaryEntity", binaryEntity);
    }
    public byte[] getBinaryEntity() {
        return (byte[])readProperty("binaryEntity");
    }
    
    
    public void setCollectionId(String collectionId) {
        writeProperty("collectionId", collectionId);
    }
    public String getCollectionId() {
        return (String)readProperty("collectionId");
    }
    
    
    public void setInCollection(String inCollection) {
        writeProperty("inCollection", inCollection);
    }
    public String getInCollection() {
        return (String)readProperty("inCollection");
    }
    
    
    public void setXml(String xml) {
        writeProperty("xml", xml);
    }
    public String getXml() {
        return (String)readProperty("xml");
    }
    
    
    public void addToParentCollection(org.sakaiproject.kernel.db.model.ContentCollection obj) {
        addToManyTarget("parentCollection", obj, true);
    }
    public void removeFromParentCollection(org.sakaiproject.kernel.db.model.ContentCollection obj) {
        removeToManyTarget("parentCollection", obj, true);
    }
    public List getParentCollection() {
        return (List)readProperty("parentCollection");
    }
    
    
}
