package org.sakaiproject.kernel.model;

/** Class _ContentDropboxChanges was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ContentDropboxChanges extends org.apache.cayenne.CayenneDataObject {

    public static final String DROPBOX_ID_PROPERTY = "dropboxId";
    public static final String IN_COLLECTION_PROPERTY = "inCollection";
    public static final String LAST_UPDATE_PROPERTY = "lastUpdate";

    public static final String ID_PK_COLUMN = "ID";

    public void setDropboxId(String dropboxId) {
        writeProperty("dropboxId", dropboxId);
    }
    public String getDropboxId() {
        return (String)readProperty("dropboxId");
    }
    
    
    public void setInCollection(String inCollection) {
        writeProperty("inCollection", inCollection);
    }
    public String getInCollection() {
        return (String)readProperty("inCollection");
    }
    
    
    public void setLastUpdate(String lastUpdate) {
        writeProperty("lastUpdate", lastUpdate);
    }
    public String getLastUpdate() {
        return (String)readProperty("lastUpdate");
    }
    
    
}
