package org.sakaiproject.kernel.model;

/** Class _ContentTypeRegistry was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ContentTypeRegistry extends org.apache.cayenne.CayenneDataObject {

    public static final String CONTEXT_ID_PROPERTY = "contextId";
    public static final String ENABLED_PROPERTY = "enabled";
    public static final String RESOURCE_TYPE_ID_PROPERTY = "resourceTypeId";

    public static final String ID_PK_COLUMN = "ID";

    public void setContextId(String contextId) {
        writeProperty("contextId", contextId);
    }
    public String getContextId() {
        return (String)readProperty("contextId");
    }
    
    
    public void setEnabled(String enabled) {
        writeProperty("enabled", enabled);
    }
    public String getEnabled() {
        return (String)readProperty("enabled");
    }
    
    
    public void setResourceTypeId(String resourceTypeId) {
        writeProperty("resourceTypeId", resourceTypeId);
    }
    public String getResourceTypeId() {
        return (String)readProperty("resourceTypeId");
    }
    
    
}
