package org.sakaiproject.kernel.model;

/** Class _SakaiCluster was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiCluster extends org.apache.cayenne.CayenneDataObject {

    public static final String UPDATE_TIME_PROPERTY = "updateTime";

    public static final String ID_PK_COLUMN = "ID";

    public void setUpdateTime(java.util.Date updateTime) {
        writeProperty("updateTime", updateTime);
    }
    public java.util.Date getUpdateTime() {
        return (java.util.Date)readProperty("updateTime");
    }
    
    
}
