package org.sakaiproject.kernel.model;

/** Class _SakaiRealmRlGr was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiRealmRlGr extends org.apache.cayenne.CayenneDataObject {

    public static final String ACTIVE_PROPERTY = "active";
    public static final String PROVIDED_PROPERTY = "provided";
    public static final String TO_SAKAI_REALM_PROPERTY = "toSakaiRealm";
    public static final String TO_SAKAI_REALM_ROLE_PROPERTY = "toSakaiRealmRole";

    public static final String REALM_KEY_PK_COLUMN = "REALM_KEY";
    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setActive(String active) {
        writeProperty("active", active);
    }
    public String getActive() {
        return (String)readProperty("active");
    }
    
    
    public void setProvided(String provided) {
        writeProperty("provided", provided);
    }
    public String getProvided() {
        return (String)readProperty("provided");
    }
    
    
    public void setToSakaiRealm(org.sakaiproject.kernel.db.model.SakaiRealm toSakaiRealm) {
        setToOneTarget("toSakaiRealm", toSakaiRealm, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiRealm getToSakaiRealm() {
        return (org.sakaiproject.kernel.db.model.SakaiRealm)readProperty("toSakaiRealm");
    } 
    
    
    public void setToSakaiRealmRole(org.sakaiproject.kernel.db.model.SakaiRealmRole toSakaiRealmRole) {
        setToOneTarget("toSakaiRealmRole", toSakaiRealmRole, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiRealmRole getToSakaiRealmRole() {
        return (org.sakaiproject.kernel.db.model.SakaiRealmRole)readProperty("toSakaiRealmRole");
    } 
    
    
}
