package org.sakaiproject.kernel.model;

/** Class _SakaiPreferences was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiPreferences extends org.apache.cayenne.CayenneDataObject {

    public static final String PREFERENCES_ID_PROPERTY = "preferencesId";
    public static final String XML_PROPERTY = "xml";

    public static final String ID_PK_COLUMN = "ID";

    public void setPreferencesId(String preferencesId) {
        writeProperty("preferencesId", preferencesId);
    }
    public String getPreferencesId() {
        return (String)readProperty("preferencesId");
    }
    
    
    public void setXml(String xml) {
        writeProperty("xml", xml);
    }
    public String getXml() {
        return (String)readProperty("xml");
    }
    
    
}
