package org.sakaiproject.kernel.model;

/** Class _SakaiSiteUser was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiSiteUser extends org.apache.cayenne.CayenneDataObject {

    public static final String PERMISSION_PROPERTY = "permission";
    public static final String TO_SAKAI_SITE_PROPERTY = "toSakaiSite";

    public static final String SITE_ID_PK_COLUMN = "SITE_ID";
    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setPermission(Integer permission) {
        writeProperty("permission", permission);
    }
    public Integer getPermission() {
        return (Integer)readProperty("permission");
    }
    
    
    public void setToSakaiSite(org.sakaiproject.kernel.db.model.SakaiSite toSakaiSite) {
        setToOneTarget("toSakaiSite", toSakaiSite, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiSite getToSakaiSite() {
        return (org.sakaiproject.kernel.db.model.SakaiSite)readProperty("toSakaiSite");
    } 
    
    
}
