package org.sakaiproject.kernel.model;

/** Class _SakaiRealmProperty was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiRealmProperty extends org.apache.cayenne.CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";
    public static final String TO_SAKAI_REALM_PROPERTY = "toSakaiRealm";

    public static final String NAME_PK_COLUMN = "NAME";
    public static final String REALM_KEY_PK_COLUMN = "REALM_KEY";

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }
    
    
    public void setToSakaiRealm(org.sakaiproject.kernel.db.model.SakaiRealm toSakaiRealm) {
        setToOneTarget("toSakaiRealm", toSakaiRealm, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiRealm getToSakaiRealm() {
        return (org.sakaiproject.kernel.db.model.SakaiRealm)readProperty("toSakaiRealm");
    } 
    
    
}
