package org.sakaiproject.kernel.model;

/** Class _SakaiUserProperty was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiUserProperty extends org.apache.cayenne.CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";
    public static final String TO_SAKAI_USER_PROPERTY = "toSakaiUser";

    public static final String NAME_PK_COLUMN = "NAME";
    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }
    
    
    public void setToSakaiUser(org.sakaiproject.kernel.db.model.SakaiUser toSakaiUser) {
        setToOneTarget("toSakaiUser", toSakaiUser, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiUser getToSakaiUser() {
        return (org.sakaiproject.kernel.db.model.SakaiUser)readProperty("toSakaiUser");
    } 
    
    
}
