package org.sakaiproject.kernel.model;

import java.util.List;

/** Class _SakaiUser was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiUser extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATEDBY_PROPERTY = "createdby";
    public static final String CREATEDON_PROPERTY = "createdon";
    public static final String EMAIL_PROPERTY = "email";
    public static final String EMAIL_LC_PROPERTY = "emailLc";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String MODIFIEDBY_PROPERTY = "modifiedby";
    public static final String MODIFIEDON_PROPERTY = "modifiedon";
    public static final String PW_PROPERTY = "pw";
    public static final String TYPE_PROPERTY = "type";
    public static final String SAKAI_USER_PROPERTY_ARRAY_PROPERTY = "sakaiUserPropertyArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreatedby(String createdby) {
        writeProperty("createdby", createdby);
    }
    public String getCreatedby() {
        return (String)readProperty("createdby");
    }
    
    
    public void setCreatedon(java.util.Date createdon) {
        writeProperty("createdon", createdon);
    }
    public java.util.Date getCreatedon() {
        return (java.util.Date)readProperty("createdon");
    }
    
    
    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }
    
    
    public void setEmailLc(String emailLc) {
        writeProperty("emailLc", emailLc);
    }
    public String getEmailLc() {
        return (String)readProperty("emailLc");
    }
    
    
    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }
    
    
    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }
    
    
    public void setModifiedby(String modifiedby) {
        writeProperty("modifiedby", modifiedby);
    }
    public String getModifiedby() {
        return (String)readProperty("modifiedby");
    }
    
    
    public void setModifiedon(java.util.Date modifiedon) {
        writeProperty("modifiedon", modifiedon);
    }
    public java.util.Date getModifiedon() {
        return (java.util.Date)readProperty("modifiedon");
    }
    
    
    public void setPw(String pw) {
        writeProperty("pw", pw);
    }
    public String getPw() {
        return (String)readProperty("pw");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void addToSakaiUserPropertyArray(org.sakaiproject.kernel.db.model.SakaiUserProperty obj) {
        addToManyTarget("sakaiUserPropertyArray", obj, true);
    }
    public void removeFromSakaiUserPropertyArray(org.sakaiproject.kernel.db.model.SakaiUserProperty obj) {
        removeToManyTarget("sakaiUserPropertyArray", obj, true);
    }
    public List getSakaiUserPropertyArray() {
        return (List)readProperty("sakaiUserPropertyArray");
    }
    
    
}
