package org.sakaiproject.kernel.model;

import java.util.List;

/** Class _SakaiRealmRole was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiRealmRole extends org.apache.cayenne.CayenneDataObject {

    public static final String ROLE_NAME_PROPERTY = "roleName";
    public static final String SAKAI_REALM_ARRAY_PROPERTY = "sakaiRealmArray";
    public static final String SAKAI_REALM_RL_FN_ARRAY_PROPERTY = "sakaiRealmRlFnArray";
    public static final String SAKAI_REALM_RL_GR_ARRAY_PROPERTY = "sakaiRealmRlGrArray";
    public static final String SAKAI_REALM_ROLE_DESC_ARRAY_PROPERTY = "sakaiRealmRoleDescArray";

    public static final String ROLE_KEY_PK_COLUMN = "ROLE_KEY";

    public void setRoleName(String roleName) {
        writeProperty("roleName", roleName);
    }
    public String getRoleName() {
        return (String)readProperty("roleName");
    }
    
    
    public void addToSakaiRealmArray(org.sakaiproject.kernel.db.model.SakaiRealm obj) {
        addToManyTarget("sakaiRealmArray", obj, true);
    }
    public void removeFromSakaiRealmArray(org.sakaiproject.kernel.db.model.SakaiRealm obj) {
        removeToManyTarget("sakaiRealmArray", obj, true);
    }
    public List getSakaiRealmArray() {
        return (List)readProperty("sakaiRealmArray");
    }
    
    
    public void addToSakaiRealmRlFnArray(org.sakaiproject.kernel.db.model.SakaiRealmRlFn obj) {
        addToManyTarget("sakaiRealmRlFnArray", obj, true);
    }
    public void removeFromSakaiRealmRlFnArray(org.sakaiproject.kernel.db.model.SakaiRealmRlFn obj) {
        removeToManyTarget("sakaiRealmRlFnArray", obj, true);
    }
    public List getSakaiRealmRlFnArray() {
        return (List)readProperty("sakaiRealmRlFnArray");
    }
    
    
    public void addToSakaiRealmRlGrArray(org.sakaiproject.kernel.db.model.SakaiRealmRlGr obj) {
        addToManyTarget("sakaiRealmRlGrArray", obj, true);
    }
    public void removeFromSakaiRealmRlGrArray(org.sakaiproject.kernel.db.model.SakaiRealmRlGr obj) {
        removeToManyTarget("sakaiRealmRlGrArray", obj, true);
    }
    public List getSakaiRealmRlGrArray() {
        return (List)readProperty("sakaiRealmRlGrArray");
    }
    
    
    public void addToSakaiRealmRoleDescArray(org.sakaiproject.kernel.db.model.SakaiRealmRoleDesc obj) {
        addToManyTarget("sakaiRealmRoleDescArray", obj, true);
    }
    public void removeFromSakaiRealmRoleDescArray(org.sakaiproject.kernel.db.model.SakaiRealmRoleDesc obj) {
        removeToManyTarget("sakaiRealmRoleDescArray", obj, true);
    }
    public List getSakaiRealmRoleDescArray() {
        return (List)readProperty("sakaiRealmRoleDescArray");
    }
    
    
}
