package org.sakaiproject.kernel.model;

import java.util.List;

/** Class _SakaiRealmFunction was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiRealmFunction extends org.apache.cayenne.CayenneDataObject {

    public static final String FUNCTION_NAME_PROPERTY = "functionName";
    public static final String SAKAI_REALM_RL_FN_ARRAY_PROPERTY = "sakaiRealmRlFnArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setFunctionName(String functionName) {
        writeProperty("functionName", functionName);
    }
    public String getFunctionName() {
        return (String)readProperty("functionName");
    }
    
    
    public void addToSakaiRealmRlFnArray(org.sakaiproject.kernel.db.model.SakaiRealmRlFn obj) {
        addToManyTarget("sakaiRealmRlFnArray", obj, true);
    }
    public void removeFromSakaiRealmRlFnArray(org.sakaiproject.kernel.db.model.SakaiRealmRlFn obj) {
        removeToManyTarget("sakaiRealmRlFnArray", obj, true);
    }
    public List getSakaiRealmRlFnArray() {
        return (List)readProperty("sakaiRealmRlFnArray");
    }
    
    
}
