package org.sakaiproject.kernel.model;

/** Class _SakaiSitePageProperty was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _SakaiSitePageProperty extends org.apache.cayenne.CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";
    public static final String TO_SAKAI_SITE_PROPERTY = "toSakaiSite";
    public static final String TO_SAKAI_SITE_PAGE_PROPERTY = "toSakaiSitePage";

    public static final String NAME_PK_COLUMN = "NAME";
    public static final String PAGE_ID_PK_COLUMN = "PAGE_ID";

    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }
    
    
    public void setToSakaiSite(org.sakaiproject.kernel.db.model.SakaiSite toSakaiSite) {
        setToOneTarget("toSakaiSite", toSakaiSite, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiSite getToSakaiSite() {
        return (org.sakaiproject.kernel.db.model.SakaiSite)readProperty("toSakaiSite");
    } 
    
    
    public void setToSakaiSitePage(org.sakaiproject.kernel.db.model.SakaiSitePage toSakaiSitePage) {
        setToOneTarget("toSakaiSitePage", toSakaiSitePage, true);
    }

    public org.sakaiproject.kernel.db.model.SakaiSitePage getToSakaiSitePage() {
        return (org.sakaiproject.kernel.db.model.SakaiSitePage)readProperty("toSakaiSitePage");
    } 
    
    
}
