<%
    request.setAttribute("html.head",
      "<link href=\"/samigo/css/tool_base.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\" />\n" +
      "<link href=\"/samigo/css/tool.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\" />\n" +
      "<link href=\"/samigo/css/tool_sam.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\" />\n");
    request.setAttribute("html.body.onload", "");
%>
