<%
    request.setAttribute("html.head",
      "<link href=\"/samigo/css/tool_base.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\" />\n" +
      "<link href=\"/samigo/css/tool.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\" />\n");
    request.setAttribute("html.body.onload", "");
/*
    request.setAttribute("html.head", request.getAttribute("sakai.html.head"));
    request.setAttribute("html.body.onload", request.getAttribute("sakai.html.body.onload"));
    request.setAttribute("html.head.sakai", request.getAttribute("sakai.html.head"));
*/
%>
