package org.sakaiproject.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-02-10T14:46:55.327-07:00
 * Generated source version: 2.7.8
 * 
 */
@WebService
@SOAPBinding(use = SOAPBinding.Use.ENCODED, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SakaiLogin {

    @WebResult(name = "loginToServerReturn", targetNamespace = "http://webservices.sakaiproject.org/", partName = "loginToServerReturn")
    @WebMethod
    public java.lang.String loginToServer(
        @WebParam(partName = "id", name = "id")
        java.lang.String id,
        @WebParam(partName = "pw", name = "pw")
        java.lang.String pw
    );

    @WebResult(name = "logoutReturn", partName = "logoutReturn")
    @WebMethod
    public boolean logout(
        @WebParam(partName = "sessionid", name = "sessionid" )
        java.lang.String sessionid
    );

    @WebResult(name = "loginReturn",partName = "loginReturn")
    @WebMethod
    public java.lang.String login(
        @WebParam(partName = "id", name = "id" )
        java.lang.String id,
        @WebParam(partName = "pw", name = "pw" )
        java.lang.String pw
    );
}
