package org.sakaiproject.tool.assessment.audio;

import java.util.*;

public class AudioResources extends java.util.ListResourceBundle
{
  private static final Object[][] contents = new String[][]{
	{ "When_running_the", "When running the Audio Recorder\n" },
	{ "_You_must_have_a", ") You must have a properly configured sound card and microphone.\n" },
	{ "_You_must_have_a1", ") You must have a properly configured Java 1.5 plugin installed.\n" },
	{ "_Have_these", ") Have these permissions added to the .java.policy file:\n\n" },
	{ "grant_", "    grant { \n" },
	{ "permission_javax", "      permission javax.sound.sampled.AudioPermission \"record\"; \n" },
	{ "permission_java_util", "      permission java.util.PropertyPermission \"user.dir\", \"read\";\n" },
	{ "permission_java_io", "      permission java.io.FilePermission \"<<ALL FILES>>\", \"read, write\";\n" },
	{ "Please_make_sure_you", "Please make sure you correct this first before using.\n\n" },
	{ "Configuration_Help", "Configuration Help" },
	{ "ABOUT_SAKAI_AUDIO", "ABOUT SAKAI AUDIO RECORDER\n\n" },
	{ "Portions_copyright_c", "Portions copyright (c) 2005 " },
	{ "The_Regents_of_the", "The Regents of the University of Michigan,\n" },
	{ "Trustees_of_Indiana", "Trustees of Indiana University, " },
	{ "Board_of_Trustees_of", "Board of Trustees of the Leland Stanford, Jr., University, " },
	{ "and_The_MIT", "and The MIT Corporation.\n\n" },
	{ "Licensed_under_the", "Licensed under the Educational Community License Version 1.0, see " +
    "\" +\n    \"\n" },
	{ "http_cvs_sakaiproject", "        http://cvs.sakaiproject.org/licenses/license_1_0.html\n\n" },
	{ "Portions_Copyright_c", "Portions Copyright (c) 1999 Sun Microsystems, Inc. All Rights Reserved.\n" },
	{ "_non_exclusive", "(non-exclusive, royalty free, license to use, modify and redistribute)" },
	{ "About_the_Audio", "About the Audio Recorder" },
	{ "Help", "Help" },
	{ "Configuration", "Configuration" },
	{ "About", "About" },
	{ "File", "File" },
	{ "Exit", "Exit" },
	{ "Audio_Recorder", "Audio Recorder" },
	{ "_audio", "./audio" },
	{ "usage_java_JavaSound", "usage: java JavaSound audioDirectory" },
	{ "Center", "Center" },
	{ "untitled", "untitled" },
	{ "Save_AU", "Save AU" },
	{ "Save_AIFF", "Save AIFF" },
	{ "Save_WAVE", "Save WAVE" },
	{ "File_to_save_", "File to save:  " },
	{ "Play", "Play" },
	{ "Record", "Record" },
	{ "Pause", "Pause" },
	{ "Load_", "Load..." },
	{ " playB_Text", "Stop" },
	{ " pausB_Text", "Resume" },
	{ "user_dir", "user.dir" },
	{ "_wav", ".wav" },
	{ "_au", ".au" },
	{ "_aif", ".aif" },
	{ "_aiff", ".aiff" },
	{ "_au_wav_aif", ".au, .wav, .aif" },
	{ "Audio_file_required_", "Audio file required." },
	{ "No_loaded_audio_to", "No loaded audio to save" },
	{ "Unable_to_reset", "Unable to reset stream " },
	{ "Problems_writing_to", "Problems writing to file" },
	{ "Capture_Playback", "Capture/Playback" },
	{ "thread_Name", "Playback" },
	{ "No_loaded_audio_to1", "No loaded audio to play back" },
	{ "Unable_to_reset_the", "Unable to reset the stream\n" },
	{ "Unable_to_convert", "Unable to convert stream of format " },
	{ "to_format", " to format " },
	{ "not_supported_", " not supported." },
	{ "Line_matching", "Line matching " },
	{ "Unable_to_open_the", "Unable to open the line: " },
	{ "Error_during_playback", "Error during playback: " },
	{ "thread_Name1", "Capture" },
	{ "linear", "linear" },
	{ "ulaw", "ulaw" },
	{ "alaw", "alaw" },
	{ "signed", "signed" },
	{ "unsigned", "unsigned" },
	{ "little_endian", "little endian" },
	{ "big_endian", "big endian" },
	{ "mono", "mono" },
	{ "stereo", "stereo" },
	{ "big", "big" },
	{ "PCM_SIGN", "PCM_SIGN" },
	{ " g2_Font", "serif" },
	{ "ERROR", "ERROR" },
	{ "Length_", "Length: " },
	{ "Length_1", "  Length: " },
	{ "File_", "File: " },
	{ "Position_", "  Position: " },
	{ "thread_Name2", "SamplingGraph" },
	{ "Applet_Information", "Applet_Information" }};
  public Object[][] getContents()
  {
    return contents;
  }
}