-- The indexes that used to be created here are declared in the Hibernate mappings
-- (SAM_ASSGRAD_AID_PUBASSEID_T in GradingData.hbm.xml, the SAM_ITEMGRADING_* indexes
-- as index attributes on the ItemGradingData properties), so there is nothing left to
-- run for this database. The file stays because SakaiBootStrap asks for it by name and
-- the loader logs a warning for a missing script.
