drop sequence MFR_RANK_S;
drop sequence MFR_RANKIMAGE_S;
drop table MFR_RANK_T;
drop table MFR_RANKIMAGE_T;


  CREATE TABLE "MFR_RANK_T" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"UUID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(99 CHAR) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(99 CHAR) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RANKTYPE" VARCHAR2(19 CHAR) NOT NULL ENABLE, 
	"ASSIGNTO" CLOB, 
	"ASSIGNTODISPLAY" CLOB, 
	"MIN_POST" NUMBER(19,0), 
	"CONTEXT_ID" VARCHAR2(99 CHAR) NOT NULL ENABLE, 
	"RANKIMAGE" NUMBER(19,0), 
	 PRIMARY KEY ("ID")
   ) ;
   
   
   
  CREATE TABLE "MFR_RANKIMAGE_T" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(99 CHAR) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(99 CHAR) NOT NULL ENABLE, 
	"ATTACHMENT_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTACHMENT_URL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTACHMENT_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTACHMENT_SIZE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTACHMENT_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RANKID" NUMBER(19,0), 
	 PRIMARY KEY ("ID")
   )  ;

create sequence MFR_RANK_S;
create sequence MFR_RANKIMAGE_S;

