
CREATE UNIQUE INDEX CONTEXT_ID  
    ON MFR_AREA_T(CONTEXT_ID, TYPE_UUID);

CREATE UNIQUE INDEX MFR_AREA_CONTEXT_UUID_UNIQUE  
    ON MFR_AREA_T(CONTEXT_ID, TYPE_UUID);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_AREA_T(ID);

CREATE INDEX FK7B2D5CDE58F99AA5  
    ON MFR_ATTACHMENT_T(m_surrogateKey);

CREATE INDEX FK7B2D5CDE5B252FAE  
    ON MFR_ATTACHMENT_T(of_urrogateKey);

CREATE INDEX FK7B2D5CDE74C7E92B  
    ON MFR_ATTACHMENT_T(of_surrogateKey);

CREATE INDEX FK7B2D5CDE7DEF8466  
    ON MFR_ATTACHMENT_T(t_surrogateKey);

CREATE INDEX FK7B2D5CDE82FAB29  
    ON MFR_ATTACHMENT_T(pf_surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_ATTACHMENT_T(ID);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_DATE_RESTRICTIONS_T(ID);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_EMAIL_NOTIFICATION_T(ID);

CREATE INDEX FK1DDE4138A306F94D  
    ON MFR_HIDDEN_GROUPS_T(a_surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_HIDDEN_GROUPS_T(ID);

CREATE INDEX FKC661154320BD9842  
    ON MFR_LABEL_T(dt_surrogateKey);

CREATE INDEX FKC661154329B20882  
    ON MFR_LABEL_T(df_surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_LABEL_T(ID);

CREATE INDEX FKE03761CB74C7E92B  
    ON MFR_MEMBERSHIP_ITEM_T(of_surrogateKey);

CREATE INDEX FKE03761CB7DEF8466  
    ON MFR_MEMBERSHIP_ITEM_T(t_surrogateKey);

CREATE INDEX FKE03761CB88085F8E  
    ON MFR_MEMBERSHIP_ITEM_T(PERMISSION_LEVEL);

CREATE INDEX FKE03761CBA306F94D  
    ON MFR_MEMBERSHIP_ITEM_T(a_surrogateKey);

CREATE UNIQUE INDEX PERMISSION_LEVEL  
    ON MFR_MEMBERSHIP_ITEM_T(PERMISSION_LEVEL);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_MEMBERSHIP_ITEM_T(ID);

CREATE INDEX FK80C1A31650339D56  
    ON MFR_MESSAGE_T(IN_REPLY_TO);

CREATE INDEX FK80C1A316A2D0BE7B  
    ON MFR_MESSAGE_T(surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_MESSAGE_T(ID);

CREATE INDEX FKC17608478B5E2A2F  
    ON MFR_OPEN_FORUM_T(surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_OPEN_FORUM_T(ID);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_PERMISSION_LEVEL_T(ID);

CREATE INDEX FKA9EE57548B5E2A2F  
    ON MFR_PRIVATE_FORUM_T(surrogateKey);

CREATE UNIQUE INDEX OWNER  
    ON MFR_PRIVATE_FORUM_T(OWNER, surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_PRIVATE_FORUM_T(ID);

CREATE INDEX FKC4DE0E1473D286ED  
    ON MFR_PVT_MSG_USR_T(messageSurrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_PVT_MSG_USR_T(messageSurrogateKey, user_index_col);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_SYNOPTIC_ITEM(SYNOPTIC_ITEM_ID);

CREATE UNIQUE INDEX USER_ID  
    ON MFR_SYNOPTIC_ITEM(USER_ID, SITE_ID);

CREATE INDEX FK863DC0BE74C7E92B  
    ON MFR_TOPIC_T(of_surrogateKey);

CREATE INDEX FK863DC0BE82FAB29  
    ON MFR_TOPIC_T(pf_surrogateKey);

CREATE INDEX FK863DC0BEFF3B3AE9  
    ON MFR_TOPIC_T(pt_surrogateKey);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_TOPIC_T(ID);

CREATE INDEX MFR_UNREAD_STATUS_I1  
    ON MFR_UNREAD_STATUS_T(TOPIC_C, MESSAGE_C, USER_C, READ_C);

CREATE INDEX MFR_UNREAD_STATUS_I2  
    ON MFR_UNREAD_STATUS_T(MESSAGE_C, USER_C, READ_C);

CREATE UNIQUE INDEX PRIMARY  
    ON MFR_UNREAD_STATUS_T(ID);

CREATE UNIQUE INDEX TOPIC_C  
    ON MFR_UNREAD_STATUS_T(TOPIC_C, MESSAGE_C, USER_C);