create index MFR_MESSAGE_T_IN_REPLY_TO_I on MFR_MESSAGE_T (IN_REPLY_TO);
create index MFR_MESSAGE_DELETED_I on MFR_MESSAGE_T (DELETED);

create index MFR_TOPIC_T_UUID_I on MFR_TOPIC_T (UUID);

create index MFR_UNREAD_STATUS_I2 on MFR_UNREAD_STATUS_T (MESSAGE_C, USER_C, READ_C);
