ALTER TABLE MFR_TOPIC_T ADD POST_ANONYMOUS NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE MFR_TOPIC_T ADD REVEAL_IDS_TO_ROLES NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE MFR_PERMISSION_LEVEL_T ADD IDENTIFY_ANON_AUTHORS NUMBER(1,0) DEFAULT 0 NOT NULL;
UPDATE MFR_PERMISSION_LEVEL_T SET IDENTIFY_ANON_AUTHORS = 1 WHERE NAME = 'Owner';
