-- Upgrade for Quartz 1.6 to 1.8

-- Drop column
ALTER TABLE QRTZ_SCHEDULER_STATE DROP COLUMN RECOVERER;

-- Increase size
ALTER TABLE QRTZ_SIMPLE_TRIGGERS MODIFY TIMES_TRIGGERED BIGINT(10) NOT NULL;

-- Increase size
ALTER TABLE QRTZ_CRON_TRIGGERS MODIFY CRON_EXPRESSION VARCHAR(120) NOT NULL;