

CREATE TABLE  "MIGRATE_CHS_CONTENT_TO_JCR" 
   (	"ID" NUMBER(10,0), 
	"CONTENT_ID" VARCHAR2(255), 
	"STATUS" NUMBER(5,0) NOT NULL DEFAULT 0, 
	"TIME_ADDED_TI_QUEUE" TIMESTAMP (6), 
	"EVENT_TYPE" VARCHAR2(32)  DEFAULT 'ORIGINAL_MIGRATION' , 
	 CONSTRAINT "MIGRATE_CHS_CONTENT_TO_JCR_PK" PRIMARY KEY ("ID") ENABLE
   )
/


CREATE OR REPLACE TRIGGER  "BI_MIGRATE_CHS_CONTENT_TO_JCR" 
  before insert on "MIGRATE_CHS_CONTENT_TO_JCR"               
  for each row  
begin   
    select "MIGRATE_CHS_CONTENT_TO_JC_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MIGRATE_CHS_CONTENT_TO_JCR" ENABLE
/

-- Indexes

CREATE INDEX MIGRATE_CHS_CONTENT_TO_JCR_STATUS_INDEX
  ON MIGRATE_CHS_CONTENT_TO_JCR(STATUS)
/
CREATE INDEX MIGRATE_CHS_CONTENT_TO_JCR_TIME_ADDED_INDEX
  ON MIGRATE_CHS_CONTENT_TO_JCR(TIME_ADDED_TO_QUEUE)
/
CREATE INDEX MIGRATE_CHS_CONTENT_TO_JCR_EVENT_TYPE_INDEX
  ON MIGRATE_CHS_CONTENT_TO_JCR(EVENT_TYPE)
/


