alter table GB_GRADE_TO_PERCENT_MAPPING_T drop constraint FKCDEA021164995486;
alter table GB_GRADE_RECORD_T drop constraint FK46ACF752B5399B44;
alter table GB_TEACHING_ASSIGNMENT_T drop constraint FKE0F822B06AB1529A;
alter table GB_TEACHING_ASSIGNMENT_T drop constraint FKE0F822B02206F20F;
alter table GB_ENROLLMENT_T drop constraint FK2D6586BD2206F20F;
alter table GB_ENROLLMENT_T drop constraint FK2D6586BD6AB1529A;
alter table GB_GRADABLE_OBJECT_T drop constraint FK759996A76AB1529A;
alter table GB_GRADE_MAP_T drop constraint FKADE112256AB1529A;
alter table GB_GRADING_EVENT_T drop constraint FK4C9D99E0B5399B44;
alter table GB_GRADEBOOK_T drop constraint FK7C870191F11270F8;
drop table GB_USER_T if exists;
drop table GB_GRADE_TO_PERCENT_MAPPING_T if exists;
drop table GB_GRADE_RECORD_T if exists;
drop table GB_TEACHING_ASSIGNMENT_T if exists;
drop table GB_ENROLLMENT_T if exists;
drop table GB_GRADABLE_OBJECT_T if exists;
drop table GB_GRADE_MAP_T if exists;
drop table GB_GRADING_EVENT_T if exists;
drop table GB_GRADEBOOK_T if exists;
create table GB_USER_T (
   ID bigint generated by default as identity (start with 1),
   AUTH_ID varchar(255) not null,
   DISPLAY_NAME varchar(255) not null,
   SORT_NAME varchar(255) not null,
   DISPLAY_UID varchar(255) not null,
   unique (AUTH_ID)
);
create table GB_GRADE_TO_PERCENT_MAPPING_T (
   GRADE_MAP_ID bigint not null,
   PERCENT double,
   LETTER_GRADE varchar(255) not null,
   primary key (GRADE_MAP_ID, LETTER_GRADE)
);
create table GB_GRADE_RECORD_T (
   ID bigint generated by default as identity (start with 1),
   OBJECT_TYPE_ID integer not null,
   VERSION integer not null,
   GRADABLE_OBJECT_ID bigint not null,
   STUDENT_ID varchar(255) not null,
   GRADER_ID varchar(255) not null,
   DATE_RECORDED timestamp not null,
   POINTS_EARNED double,
   ENTERED_GRADE varchar(255),
   SORT_GRADE double
   unique (GRADABLE_OBJECT_ID, STUDENT_ID)
);
create table GB_TEACHING_ASSIGNMENT_T (
   ID bigint generated by default as identity (start with 1),
   GRADEBOOK_ID bigint not null,
   USER_ID bigint not null,
   unique (GRADEBOOK_ID, USER_ID)
);
create table GB_ENROLLMENT_T (
   ID bigint generated by default as identity (start with 1),
   GRADEBOOK_ID bigint not null,
   USER_ID bigint not null,
   unique (GRADEBOOK_ID, USER_ID)
);
create table GB_GRADABLE_OBJECT_T (
   ID bigint generated by default as identity (start with 1),
   OBJECT_TYPE_ID integer not null,
   VERSION integer not null,
   GRADEBOOK_ID bigint not null,
   NAME varchar(255) not null,
   REMOVED bit,
   POINTS_POSSIBLE double,
   DUE_DATE date,
   NOT_COUNTED bit,
   EXTERNALLY_MAINTAINED bit,
   EXTERNAL_STUDENT_LINK varchar(255),
   EXTERNAL_INSTRUCTOR_LINK varchar(255),
   EXTERNAL_ID varchar(255),
   EXTERNAL_APP_NAME varchar(255)
);
create table GB_GRADE_MAP_T (
   ID bigint generated by default as identity (start with 1),
   OBJECT_TYPE_ID integer not null,
   VERSION integer not null,
   GRADEBOOK_ID bigint not null
);
create table GB_GRADING_EVENT_T (
   ID bigint generated by default as identity (start with 1),
   GRADABLE_OBJECT_ID bigint not null,
   GRADER_ID varchar(255) not null,
   STUDENT_ID varchar(255) not null,
   DATE_GRADED timestamp not null,
   GRADE varchar(255)
);
create table GB_GRADEBOOK_T (
   ID bigint generated by default as identity (start with 1),
   VERSION integer not null,
   GRADEBOOK_UID varchar(255) not null,
   NAME varchar(255) not null,
   SELECTED_GRADE_MAPPING_ID bigint,
   ASSIGNMENTS_DISPLAYED bit not null,
   COURSE_GRADE_DISPLAYED bit not null,
   ALL_ASSIGNMENTS_ENTERED bit not null,
   LOCKED bit not null,
   unique (GRADEBOOK_UID)
);
alter table GB_GRADE_TO_PERCENT_MAPPING_T add constraint FKCDEA021164995486 foreign key (GRADE_MAP_ID) references GB_GRADE_MAP_T;
alter table GB_GRADE_RECORD_T add constraint FK46ACF752B5399B44 foreign key (GRADABLE_OBJECT_ID) references GB_GRADABLE_OBJECT_T;
alter table GB_TEACHING_ASSIGNMENT_T add constraint FKE0F822B06AB1529A foreign key (GRADEBOOK_ID) references GB_GRADEBOOK_T;
alter table GB_TEACHING_ASSIGNMENT_T add constraint FKE0F822B02206F20F foreign key (USER_ID) references GB_USER_T;
alter table GB_ENROLLMENT_T add constraint FK2D6586BD2206F20F foreign key (USER_ID) references GB_USER_T;
alter table GB_ENROLLMENT_T add constraint FK2D6586BD6AB1529A foreign key (GRADEBOOK_ID) references GB_GRADEBOOK_T;
alter table GB_GRADABLE_OBJECT_T add constraint FK759996A76AB1529A foreign key (GRADEBOOK_ID) references GB_GRADEBOOK_T;
alter table GB_GRADE_MAP_T add constraint FKADE112256AB1529A foreign key (GRADEBOOK_ID) references GB_GRADEBOOK_T;
alter table GB_GRADING_EVENT_T add constraint FK4C9D99E0B5399B44 foreign key (GRADABLE_OBJECT_ID) references GB_GRADABLE_OBJECT_T;
alter table GB_GRADEBOOK_T add constraint FK7C870191F11270F8 foreign key (SELECTED_GRADE_MAPPING_ID) references GB_GRADE_MAP_T;
create index GB_GRADE_RECORD_G_O_IDX on GB_GRADE_RECORD_T (GRADABLE_OBJECT_ID);
create index GB_GRADE_RECORD_STUDENT_ID_IDX on GB_GRADE_RECORD_T (STUDENT_ID);
