
    create table SimplePageTool (
        id bigint generated by default as identity (start with 1),
        pageId varchar(250),
        sequence integer,
        sakaiId varchar(250),
        primary key (id)
    );
