alter table SAKAI_HELP_RESOURCE drop constraint FKC23F5132DBFCB7FC
drop table SAKAI_HELP_CATEGORY if exists
drop table SAKAI_HELP_RESOURCE if exists
create table SAKAI_HELP_CATEGORY (
   id bigint generated by default as identity (start with 1),
   NAME varchar(255) not null,
   unique (NAME)
)
create table SAKAI_HELP_RESOURCE (
   id bigint generated by default as identity (start with 1),
   document_id varchar(36) not null,
   NAME varchar(255),
   LOCATION varchar(255),
   CATEGORY_ID bigint not null,
   unique (document_id)
)
create index help_cat_idx on SAKAI_HELP_RESOURCE (NAME)
alter table SAKAI_HELP_RESOURCE add constraint FKC23F5132DBFCB7FC foreign key (CATEGORY_ID) references SAKAI_HELP_CATEGORY
