perm-assessment.takeAssessment=Take assessments
perm-assessment.submitAssessmentForGrade=Submit assessments for grading
perm-assessment.createAssessment=Create assessments
perm-assessment.editAssessment.any=Edit any assessment
perm-assessment.editAssessment.own=Edit own assessments
perm-assessment.deleteAssessment.any=Delete any assessment
perm-assessment.deleteAssessment.own=Delete own assessments
perm-assessment.publishAssessment.any=Publish any assessment
perm-assessment.publishAssessment.own=Publish own assessments
perm-assessment.gradeAssessment.any=Grade any assessment
perm-assessment.gradeAssessment.own=Grade own assessments
perm-assessment.questionpool.create=Create question pools
perm-assessment.questionpool.edit.own=Edit own question pools
perm-assessment.questionpool.delete.own=Delete own question pools
perm-assessment.questionpool.copy.own=Copy own question pools
perm-assessment.template.create=Create assessment types
perm-assessment.template.edit.own=Edit own assessment types
perm-assessment.template.delete.own=Delete own assessment types
perm-assessment.all.groups=Access all groups
