CREATE TABLE SAKAI_EVENT_DELAY 
( 
    EVENT_DELAY_ID BIGINT NOT NULL, 
    EVENT VARCHAR (32), 
    RESOURCE VARCHAR (255), 
    USER_ID VARCHAR (99), 
    MODIFY VARCHAR(5),
    PRIORITY INT 
); 
	 	 
ALTER TABLE  SAKAI_EVENT_DELAY 
    ADD  PRIMARY KEY (EVENT_DELAY_ID)  ; 
	 	 
CREATE INDEX IE_EVENT_DELAY_RES ON SAKAI_EVENT_DELAY 
( 
    RESOURCE ASC 
); 
