<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.sakaiproject</groupId>
        <artifactId>master</artifactId>
        <version>27-SNAPSHOT</version>
        <relativePath>../master/pom.xml</relativePath>
    </parent>

    <groupId>org.sakaiproject</groupId>
    <artifactId>libs</artifactId>
    <packaging>pom</packaging>

    <name>Sakai Vendored Libraries Base POM</name>
    <description>Third-party libraries forked into the Sakai source tree and maintained by Sakai</description>

    <modules>
        <module>pluto</module>
        <module>tomahawk</module>
    </modules>

</project>
