-- SAK-29571 MFR_MESSAGE_DELETD_I causes bad performance
drop index MFR_MESSAGE_DELETED_I;
-- END SAK-29571 MFR_MESSAGE_DELETD_I causes bad performance

--KNL-1379 Bigger SESSION_USER_AGENT
ALTER TABLE SAKAI_SESSION MODIFY SESSION_USER_AGENT VARCHAR2 (255 CHAR);
-- END KNL-1379
