-- SAM-2428
-- You should execute this sentence only if you have this object in your database.
-- This is probably the case if you had running a Sakai 10 release prior to Sakai 10.3.
-- RENAME SAM_EVENTLOG_T_SEQ TO SAM_EVENTLOG_ID_S;