-- SAM-2259 Optimizing Samigo question pool performance 
ALTER TABLE SAM_QUESTIONPOOLITEM_T CHANGE COLUMN ITEMID ITEMID bigint(20);
ALTER TABLE SAM_QUESTIONPOOLITEM_T ADD INDEX SAM_IDX_ITEMID (ITEMID);
ALTER TABLE SAM_AUTHZDATA_T DROP INDEX sam_authz_functionId_idx;
ALTER TABLE SAM_AUTHZDATA_T DROP INDEX sam_authz_qualifierId_idx;
ALTER TABLE SAM_AUTHZDATA_T ADD INDEX SAM_IDX_FUNC_QUAL (FUNCTIONID,QUALIFIERID);
ALTER TABLE SAM_AUTHZDATA_T MODIFY COLUMN AGENTID varchar(99);
ALTER TABLE SAM_AUTHZDATA_T MODIFY COLUMN LASTMODIFIEDBY varchar(99);
-- End SAM-2259
