-- BEGIN SAM-3066 remove unecessary indexes because Hibernate always create an index on an FK
DROP INDEX SAM_PUBITEM_SECTION_I;
DROP INDEX SAM_PUBITEMFB_ITEM_I;
DROP INDEX SAM_PUBITEMMETA_ITEM_I;
DROP INDEX SAM_PUBITEMTEXT_ITEM_I;
DROP INDEX SAM_PUBSECTION_ASSESSMENT_I;
DROP INDEX SAM_PUBITEM_SECTION_I;
DROP INDEX SAM_PUBIP_ASSESSMENT_I;
DROP INDEX SAM_PUBSECTIONMETA_SECTION_I;
DROP INDEX SAM_ANSWER_ITEMTEXTID_I;
-- END SAM-3066
