-- BEGIN SAM-3066 remove unecessary indexes because Hibernate always create an index on an FK
ALTER TABLE SAM_PUBLISHEDITEM_T DROP INDEX SAM_PUBITEM_SECTION_I;
ALTER TABLE SAM_PUBLISHEDITEMFEEDBACK_T DROP INDEX SAM_PUBITEMFB_ITEM_I;
ALTER TABLE SAM_PUBLISHEDITEMMETADATA_T DROP INDEX SAM_PUBITEMMETA_ITEM_I;
ALTER TABLE SAM_PUBLISHEDITEMTEXT_T DROP INDEX SAM_PUBITEMTEXT_ITEM_I;
ALTER TABLE SAM_PUBLISHEDSECTION_T DROP INDEX SAM_PUBSECTION_ASSESSMENT_I;
ALTER TABLE SAM_PUBSECTION_ASSESSMENT_I DROP INDEX SAM_PUBITEM_SECTION_I;
ALTER TABLE SAM_PUBLISHEDSECUREDIP_T DROP INDEX SAM_PUBIP_ASSESSMENT_I;
ALTER TABLE SAM_PUBLISHEDSECTIONMETADATA_T DROP INDEX SAM_PUBSECTIONMETA_SECTION_I;
ALTER TABLE SAM_ANSWER_T DROP INDEX SAM_ANSWER_ITEMTEXTID_I;
-- END SAM-3066

-- SAK-31136 some old Sakai MySQL databases have shorter data limits 
ALTER TABLE MFR_MESSAGE_T MODIFY BODY LONGTEXT;
ALTER TABLE MFR_TOPIC_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_OPEN_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY EXTENDED_DESCRIPTION LONGTEXT;
-- END SAK-31136

