-- SAM-787 Incorrect internationalization in survey questions
-- MAKE SURE YOUR DATABASE CONNECTION IS USING THE UTF-8 CHARACTER SET!!!!
-- 
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='نعم';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='لا';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='موافق';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='غير موافق';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='متردد';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='دون المعدل';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='معدل';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='فوق المتوسط';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='أختلف بشدة';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='أوافق بشدة';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='غير مقبول';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='ممتاز';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='نعم';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='لا';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='موافق';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='غير موافق';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='متردد';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='دون المعدل';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='معدل';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='فوق المتوسط';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='أختلف بشدة';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='أوافق بشدة';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='غير مقبول';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='ممتاز';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sí';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='No';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='D''acord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='en desacord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Indecís';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Per sota de la mitjana';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Dins de la mitjana';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Per sobre de la mitjana';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Molt en desacord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Molt d''acord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inacceptable';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excel·lent';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sí';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='No';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='D''acord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='en desacord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Indecís';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Per sota de la mitjana';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Dins de la mitjana';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Per sobre de la mitjana';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Molt en desacord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Molt d''acord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inacceptable';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excel·lent';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Yes';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='No';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Agree';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Disagree';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Undecided';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Below Average ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Average ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Above Average';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Strongly Disagree';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Strongly Agree';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Unacceptable';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excellent';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Yes';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='No';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Agree';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Disagree';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Undecided';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Below Average ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Average ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Above Average';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Strongly Disagree';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Strongly Agree';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Unacceptable';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excellent';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sí';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='No';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Acuerdo';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='En desacuerdo';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='NS/NC';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Por debajo de la media';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Media';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Por encima de la media';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totalmente en desacuerdo';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totalmente de acuerdo';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inaceptable';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excelente';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sí';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='No';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Acuerdo';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='En desacuerdo';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='NS/NC';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Por debajo de la media';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Media';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Por encima de la media';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totalmente en desacuerdo';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totalmente de acuerdo';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inaceptable';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excelente';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Bai';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ez';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ados';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ez ados';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Erabaki gabe';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Behean batez bestekoa ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Batez bestekoa';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Goian batez bestekoa';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Batere ez ados';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Oso ados';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Onartezin';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Bikain';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Bai';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ez';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ados';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ez ados';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Erabaki gabe';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Behean batez bestekoa ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Batez bestekoa';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Goian batez bestekoa';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Batere ez ados';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Oso ados';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Onartezin';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Bikain';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Oui';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Non';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Accepter';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='En désaccord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Indécis';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sous la moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Au-dessus de la moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totalement en désaccord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totallement en accord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inacceptable';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excellent';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Oui';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Non';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Accepter';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='En désaccord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Indécis';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sous la moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Au-dessus de la moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totalement en désaccord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totallement en accord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inacceptable';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excellent';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Oui';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Non';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Accepter';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='En désaccord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Indécis';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sous la moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Au-dessus de la moyenne';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totalement en désaccord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Totalement en accord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inacceptable';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excellent';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Oui';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Non';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Accepter';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='En désaccord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Indécis';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sous la moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Au-dessus de la moyenne';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totalement en désaccord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Totalement en accord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inacceptable';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excellent';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='はい';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='いいえ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='認めます';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='認められません';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='まだ分かりません';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='平均より下';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='平均';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='平均より上';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='全く認められません';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='完全に認めます';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='許容できません';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='優秀';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='はい';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='いいえ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='認めます';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='認められません';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='まだ分かりません';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='平均より下';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='平均';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='平均より上';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='全く認められません';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='完全に認めます';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='許容できません';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='優秀';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Тийн';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Үгүй';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Зөвшөөрч байна';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Зөвшөөрөхгүй байна';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Шийдээгүй';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Дундажаас доош';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Дундаж';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Дундажаас дээш';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Үл Зөвшөөрөхгүй байна';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Баттай Зөвшөөрч байна';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Хүлээн авах боломжгүй';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Онц';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Тийн';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Үгүй';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Зөвшөөрч байна';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Зөвшөөрөхгүй байна';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Шийдээгүй';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Дундажаас доош';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Дундаж';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Дундажаас дээш';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Үл Зөвшөөрөхгүй байна';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Баттай Зөвшөөрч байна';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Хүлээн авах боломжгүй';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Онц';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ja';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Nee';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Akkoord';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Oneens';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Onbeslist';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Onder het gemiddelde';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Gemiddeld';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Bovengemiddeld';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Volledig oneens';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Volledig eens';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Onaanvaardbaar';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Uitmuntend';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ja';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Nee';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Akkoord';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Oneens';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Onbeslist';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Onder het gemiddelde';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Gemiddeld';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Bovengemiddeld';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Volledig oneens';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Volledig eens';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Onaanvaardbaar';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Uitmuntend';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sim';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Não';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Concorda';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Discorda';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Indeciso ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Abaixo da Média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Acima da Média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Discorda Fortemente ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Concorda Fortemente';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inaceitável ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excelente ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sim';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Não';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Concorda';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Discorda';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Indeciso ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Abaixo da Média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Acima da Média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Discorda Fortemente ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Concorda Fortemente';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inaceitável ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excelente ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sim';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Não';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Concordar';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Discorda';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Sem decisão';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Abaixo da média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Acima da média';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Discordo plenamente';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Concordo plenamente';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Inaceitável';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Excelente';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sim';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Não';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Concordar';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Discorda';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Sem decisão';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Abaixo da média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Acima da média';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Discordo plenamente';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Concordo plenamente';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Inaceitável';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Excelente';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Да';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Нет';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Согласен';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Не согласен';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Затрудняюсь ответить';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ниже среднего ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Средне ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Выше среднего';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Категорически не согласен';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Полностью согласен';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Неприемлемо';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Отлично';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Да';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Нет';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Согласен';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Не согласен';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Затрудняюсь ответить';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ниже среднего ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Средне ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Выше среднего';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Категорически не согласен';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Полностью согласен';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Неприемлемо';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Отлично';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ja';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Nej';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Håller delvis med';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Håller inte med';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Tveksam';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Under medel ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Medel';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Över medel';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Håller absolut inte med';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Håller absolut med';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Oacceptabelt';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Utmärkt';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ja';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Nej';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Håller delvis med';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Håller inte med';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Tveksam';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Under medel ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Medel';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Över medel';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Håller absolut inte med';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Håller absolut med';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Oacceptabelt';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Utmärkt';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Evet';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Hayır';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Katılıyorum';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Katılmıyorum';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Kararsızım';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ortalamanın Altında';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ortalama';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Ortalamanın Üstünde';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Kesinlikle Katılmıyorum';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Kesinlikle Katılıyorum';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Kabul Edilemez';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='Çok İyi';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Evet';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Hayır';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Katılıyorum';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Katılmıyorum';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Kararsızım';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ortalamanın Altında';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ortalama';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Ortalamanın Üstünde';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Kesinlikle Katılmıyorum';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Kesinlikle Katılıyorum';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Kabul Edilemez';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='Çok İyi';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='是';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='否';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='同意';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不同意';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不确定';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='低于平均水平';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='平均水平';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='高于平均水平';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='非常不同意';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='非常同意';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不可接受';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='优秀';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='是';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='否';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='同意';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不同意';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不确定';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='低于平均水平';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='平均水平';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='高于平均水平';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='非常不同意';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='非常同意';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不可接受';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='优秀';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_yes'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='是 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_no'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='否 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='同意 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不同意 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_undecided'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不確定 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_below_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='低於平均值 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='平均 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_above_average'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='高於平均值 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='非常不同意 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='非常同意 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_unacceptable'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='不接受 ';
update SAM_ANSWER_T, SAM_ITEM_T  SET SAM_ANSWER_T.TEXT='st_excellent'
WHERE SAM_ITEM_T.ITEMID=SAM_ANSWER_T.ITEMID AND SAM_ITEM_T.TYPEID=3 AND SAM_ANSWER_T.TEXT='非常好 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_yes'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='是 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_no'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='否 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='同意 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不同意 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_undecided'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不確定 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_below_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='低於平均值 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='平均 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_above_average'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='高於平均值 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_disagree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='非常不同意 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_strongly_agree'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='非常同意 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_unacceptable'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='不接受 ';
update SAM_PUBLISHEDANSWER_T, SAM_PUBLISHEDITEM_T  SET SAM_PUBLISHEDANSWER_T.TEXT='st_excellent'
WHERE SAM_PUBLISHEDITEM_T.ITEMID=SAM_PUBLISHEDANSWER_T.ITEMID AND SAM_PUBLISHEDITEM_T.TYPEID=3 AND SAM_PUBLISHEDANSWER_T.TEXT='非常好 ';
