-- User related tables changes needed after 2.1.0.004
ALTER TABLE SAKAI_USER ADD EMAIL_LC VARCHAR (255);
UPDATE SAKAI_USER SET EMAIL_LC = LOWER(EMAIL);
DROP INDEX IE_SAKAI_USER_EMAIL;
CREATE INDEX IE_SAKAI_USER_EMAIL ON SAKAI_USER( EMAIL_LC ASC );
