CREATE TABLE COMMONS_COMMONS (
  ID varchar2(36) NOT NULL,
  SITE_ID varchar2(99) NOT NULL,
  EMBEDDER varchar2(24) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COMMONS_COMMONS_POST (
  COMMONS_ID varchar2(36) DEFAULT NULL,
  POST_ID varchar2(36) DEFAULT NULL,
  CONSTRAINT UK_COMMONS_ID_POST_ID UNIQUE (COMMONS_ID,POST_ID)
);

CREATE TABLE COMMONS_POST (
  ID varchar2(36) NOT NULL,
  CONTENT clob NOT NULL,
  CREATOR_ID varchar2(99) NOT NULL,
  CREATED_DATE timestamp NOT NULL,
  MODIFIED_DATE timestamp NOT NULL,
  RELEASE_DATE timestamp NOT NULL,
  PRIORITY NUMBER(1) DEFAULT 0 NOT NULL
  PRIMARY KEY (ID)
);

CREATE TABLE COMMONS_COMMENT (
  ID varchar2(36) NOT NULL,
  POST_ID varchar2(36) DEFAULT NULL,
  CONTENT clob NOT NULL,
  CREATOR_ID varchar2(99) NOT NULL,
  CREATED_DATE timestamp NOT NULL,
  MODIFIED_DATE timestamp NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE COMMONS_LIKE (
  USER_ID VARCHAR2(99) NOT NULL,
  POST_ID VARCHAR2(36) NOT NULL,
  VOTE NUMBER(1) DEFAULT 0 NOT NULL,
  MODIFIED_DATE TIMESTAMP(6),
  CONSTRAINT commons_like_pk PRIMARY KEY (USER_ID, POST_ID)
);

CREATE INDEX IDX_COMMONS_CREATOR ON COMMONS_COMMENT(CREATOR_ID);
CREATE INDEX IDX_COMMONS_POST ON COMMONS_COMMENT(POST_ID);
CREATE INDEX IDX_COMMONS_POST_CREATOR ON COMMONS_POST(CREATOR_ID);
