svn cleanup .
svn rm alias/alias-api/api/
svn rm alias/alias-impl/impl/
svn rm alias/alias-impl/pack/
svn cleanup .
svn rm authz/authz-api/api/
svn rm authz/authz-impl/impl/
svn rm authz/authz-impl/integration-test/
svn rm authz/authz-impl/pack/
svn cleanup .
svn rm cluster
svn cleanup .
svn rm component
svn cleanup .
svn rm content/content-api/api/
svn rm content/content-impl/hbm/
svn rm content/content-impl/impl/
svn rm content/content-impl/pack/
svn rm content/content-impl-jcr/impl/
svn rm content/content-impl-jcr/pack/
svn rm content/content-jcr-migration-api/
svn rm content/content-jcr-migration-impl/
svn rm content/content-test/
svn rm content/content-util/util/
svn rm content/contentmultiplex-impl/impl/
svn cleanup .
svn rm db
svn cleanup .
svn rm email/email-api/api/
svn rm email/email-impl/impl/
svn rm email/email-impl/pack/
svn rm email/email-shared-deploy/
svn rm email/pom.xml
svn cleanup .
svn rm entity
svn cleanup .
svn rm event
svn cleanup .
svn rm jcr
svn cleanup .
svn rm memory/memory-api/api/
svn rm memory/memory-impl/impl/
svn rm memory/memory-impl/pack/
svn cleanup .
svn rm site/site-api/api/
svn rm site/site-impl/impl/
svn rm site/site-impl/pack/
svn cleanup .
svn rm tool/tool-api/api/
svn rm tool/tool-impl/impl/
svn rm tool/tool-impl/pack/
svn rm tool/tool-shared-deploy/
svn rm tool/tool-util/servlet/
svn rm tool/tool-util/util/
svn cleanup .
svn rm user/user-api/api/
svn rm user/user-impl/impl/
svn rm user/user-impl/integration-test/
svn rm user/user-impl/pack/
svn rm user/user-util/util/
svn cleanup .
svn rm util


svn cleanup .
svn propget svn:externals | grep -v "^cluster" | grep -v "^component" | grep -v "^db" | grep -v "^entity" | grep -v "^event" | grep -v "^jcr" | grep -v "^util" > .externals
svn propset svn:externals --file .externals .
