version: '3.6'
services:
  sakai:
    image: sakai
    ports:
      - "8080:8080"
    configs:
      - source: sakai_config
        target: /usr/local/sakai/properties/sakai.properties
    secrets:
      - security.properties

  mysql:
    image: mysql:5.5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: examplerootpassword
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: examplepassword

secrets:
  security.properties:
    file: ./secrets/security.properties

configs:
  sakai_config:
    file: ./config/sakai.properties
