-----------------------------------------------------------------------------
-- CONTENT_RESOURCE_BODY_BINARY_DELETE
-- TODO: add CONTENT_RESOURCE_BODY_BINARY_DELETE table if required
-----------------------------------------------------------------------------

CREATE TABLE CONTENT_RESOURCE_DELETE
(
    RESOURCE_ID VARCHAR (255) NOT NULL,
    RESOURCE_UUID VARCHAR (36),
	IN_COLLECTION VARCHAR (255),
	FILE_PATH VARCHAR (128),
	DELETE_DATE DATE,
	DELETE_USERID VARCHAR (36),
    XML LONGVARCHAR,
    CONSTRAINT CONTENT_RESOURCE_UUID_DELETE_I UNIQUE (RESOURCE_UUID)
);

CREATE INDEX CONTENT_RESOURCE_DELETE_INDEX ON CONTENT_RESOURCE_DELETE
(
	RESOURCE_ID
);

