CREATE TABLE SAKAI_SESSION
(
	SESSION_ID VARCHAR (36),
	SESSION_SERVER VARCHAR (255),
	SESSION_USER VARCHAR (99),
	SESSION_IP VARCHAR (128),
	SESSION_HOSTNAME VARCHAR (255),
	SESSION_USER_AGENT VARCHAR (255),
	SESSION_START DATETIME,
	SESSION_END DATETIME,
	SESSION_ACTIVE bit,
	CONSTRAINT SAKAI_SESSION_INDEX UNIQUE (SESSION_ID)
);

CREATE TABLE SAKAI_EVENT
(
	EVENT_ID INT,
	EVENT_DATE DATE,
	EVENT VARCHAR (32),
	REF VARCHAR (255),
	CONTEXT VARCHAR (255),
	SESSION_ID VARCHAR (163),
	EVENT_CODE VARCHAR (1),
	PRIMARY KEY (EVENT_ID)
);

INSERT INTO SAKAI_SESSION VALUES('session-1', 'server-1', 'users-1','127.0.0.1', null, 'test', NOW(), NOW(), 0 );
INSERT INTO SAKAI_EVENT VALUES(1, NOW(), 'user.login', '', '', 'session-1', 'm');


