background_color=Background Color
close=Close
colors=Colors
foreground_color=Foreground Color
image=Image
info=Edit the course card settings for {0}
save_changes=Save Changes
save_error=Failed to save card settings
settings=Course Card Settings
