	
ALTER TABLE MFR_AREA_T
	ADD CONSTRAINT MFR_AREA_CONTEXT_UUID_UNIQUE
	UNIQUE (CONTEXT_ID, TYPE_UUID);

ALTER TABLE MFR_ATTACHMENT_T
	ADD CONSTRAINT FK7B2D5CDE82FAB29
	FOREIGN KEY(pf_surrogateKey)
	REFERENCES mfr_private_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_ATTACHMENT_T
	ADD CONSTRAINT FK7B2D5CDE7DEF8466
	FOREIGN KEY(t_surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_ATTACHMENT_T
	ADD CONSTRAINT FK7B2D5CDE74C7E92B
	FOREIGN KEY(of_surrogateKey)
	REFERENCES mfr_open_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_ATTACHMENT_T
	ADD CONSTRAINT FK7B2D5CDE5B252FAE
	FOREIGN KEY(of_urrogateKey)
	REFERENCES mfr_open_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_ATTACHMENT_T
	ADD CONSTRAINT FK7B2D5CDE58F99AA5
	FOREIGN KEY(m_surrogateKey)
	REFERENCES mfr_message_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FK7B2D5CDE82FAB29 
	ON MFR_ATTACHMENT_T(pf_surrogateKey);
CREATE INDEX FK7B2D5CDE74C7E92B 
	ON MFR_ATTACHMENT_T(of_surrogateKey);
CREATE INDEX FK7B2D5CDE7DEF8466 
	ON MFR_ATTACHMENT_T(t_surrogateKey);
CREATE INDEX FK7B2D5CDE5B252FAE 
	ON MFR_ATTACHMENT_T(of_urrogateKey);
CREATE INDEX FK7B2D5CDE58F99AA5 
	ON MFR_ATTACHMENT_T(m_surrogateKey);
	
	
CREATE INDEX FK1DDE4138A306F94D 
	ON mfr_hidden_groups_t(a_surrogateKey);
	    
    
ALTER TABLE MFR_MESSAGE_T
	ADD CONSTRAINT FK80C1A316A2D0BE7B
	FOREIGN KEY(surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_MESSAGE_T
	ADD CONSTRAINT FK80C1A31650339D56
	FOREIGN KEY(IN_REPLY_TO)
	REFERENCES mfr_message_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FK80C1A316A2D0BE7B 
	ON MFR_MESSAGE_T(surrogateKey);
CREATE INDEX FK80C1A31650339D56 
	ON MFR_MESSAGE_T(IN_REPLY_TO);
    
    
ALTER TABLE MFR_LABEL_T
	ADD CONSTRAINT FKC661154329B20882
	FOREIGN KEY(df_surrogateKey)
	REFERENCES mfr_open_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_LABEL_T
	ADD CONSTRAINT FKC661154320BD9842
	FOREIGN KEY(dt_surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FKC661154329B20882 
	ON MFR_LABEL_T(df_surrogateKey);
CREATE INDEX FKC661154320BD9842 
	ON MFR_LABEL_T(dt_surrogateKey);
	
ALTER TABLE MFR_MEMBERSHIP_ITEM_T
	ADD CONSTRAINT PERMISSION_LEVEL
	UNIQUE (PERMISSION_LEVEL);
ALTER TABLE MFR_MEMBERSHIP_ITEM_T
	ADD CONSTRAINT FKE03761CBA306F94D
	FOREIGN KEY(a_surrogateKey)
	REFERENCES mfr_area_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_MEMBERSHIP_ITEM_T
	ADD CONSTRAINT FKE03761CB88085F8E
	FOREIGN KEY(PERMISSION_LEVEL)
	REFERENCES mfr_permission_level_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_MEMBERSHIP_ITEM_T
	ADD CONSTRAINT FKE03761CB7DEF8466
	FOREIGN KEY(t_surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_MEMBERSHIP_ITEM_T
	ADD CONSTRAINT FKE03761CB74C7E92B
	FOREIGN KEY(of_surrogateKey)
	REFERENCES mfr_open_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FKE03761CB88085F8E 
	ON MFR_MEMBERSHIP_ITEM_T(PERMISSION_LEVEL);
CREATE INDEX FKE03761CBA306F94D 
	ON MFR_MEMBERSHIP_ITEM_T(a_surrogateKey);
CREATE INDEX FKE03761CB7DEF8466 
	ON MFR_MEMBERSHIP_ITEM_T(t_surrogateKey);
CREATE INDEX FKE03761CB74C7E92B 
	ON MFR_MEMBERSHIP_ITEM_T(of_surrogateKey);
	
	
ALTER TABLE MFR_MESSAGE_T
	ADD CONSTRAINT FK80C1A316A2D0BE7B
	FOREIGN KEY(surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_MESSAGE_T
	ADD CONSTRAINT FK80C1A31650339D56
	FOREIGN KEY(IN_REPLY_TO)
	REFERENCES mfr_message_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FK80C1A316A2D0BE7B 
	ON MFR_MESSAGE_T(surrogateKey);
CREATE INDEX FK80C1A31650339D56 
	ON MFR_MESSAGE_T(IN_REPLY_TO);
	
	
ALTER TABLE MFR_OPEN_FORUM_T
	ADD CONSTRAINT FKC17608478B5E2A2F
	FOREIGN KEY(surrogateKey)
	REFERENCES mfr_area_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FKC17608478B5E2A2F 
	ON MFR_OPEN_FORUM_T(surrogateKey);

	
ALTER TABLE MFR_PRIVATE_FORUM_T
	ADD CONSTRAINT OWNER
	UNIQUE (OWNER, surrogateKey);
ALTER TABLE MFR_PRIVATE_FORUM_T
	ADD CONSTRAINT FKA9EE57548B5E2A2F
	FOREIGN KEY(surrogateKey)
	REFERENCES mfr_area_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FKA9EE57548B5E2A2F 
	ON MFR_PRIVATE_FORUM_T(surrogateKey);
	
ALTER TABLE MFR_PVT_MSG_USR_T
	ADD CONSTRAINT FKC4DE0E1473D286ED
	FOREIGN KEY(messageSurrogateKey)
	REFERENCES mfr_message_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FKC4DE0E1473D286ED 
	ON MFR_PVT_MSG_USR_T(messageSurrogateKey);
	
ALTER TABLE MFR_SYNOPTIC_ITEM
	ADD CONSTRAINT USER_ID
	UNIQUE (USER_ID, SITE_ID);
	
ALTER TABLE MFR_TOPIC_T
	ADD CONSTRAINT FK863DC0BEFF3B3AE9
	FOREIGN KEY(pt_surrogateKey)
	REFERENCES mfr_topic_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_TOPIC_T
	ADD CONSTRAINT FK863DC0BE82FAB29
	FOREIGN KEY(pf_surrogateKey)
	REFERENCES mfr_private_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
ALTER TABLE MFR_TOPIC_T
	ADD CONSTRAINT FK863DC0BE74C7E92B
	FOREIGN KEY(of_surrogateKey)
	REFERENCES mfr_open_forum_t(ID)
	ON DELETE RESTRICT 
	ON UPDATE RESTRICT ;
CREATE INDEX FK863DC0BEFF3B3AE9 
	ON MFR_TOPIC_T(pt_surrogateKey);
CREATE INDEX FK863DC0BE82FAB29 
	ON MFR_TOPIC_T(pf_surrogateKey);
CREATE INDEX FK863DC0BE74C7E92B 
	ON MFR_TOPIC_T(of_surrogateKey);
	
ALTER TABLE MFR_UNREAD_STATUS_T
	ADD CONSTRAINT TOPIC_C
	UNIQUE (TOPIC_C, MESSAGE_C, USER_C);
CREATE INDEX MFR_UNREAD_STATUS_I1 
	ON MFR_UNREAD_STATUS_T(TOPIC_C, MESSAGE_C, USER_C, READ_C);
CREATE INDEX MFR_UNREAD_STATUS_I2 
	ON MFR_UNREAD_STATUS_T(MESSAGE_C, USER_C, READ_C);