drop table SAKAI_PRIVACY_RECORD if exists;
create table SAKAI_PRIVACY_RECORD (id bigint generated by default as identity (start with 1), lockId integer not null, contextId varchar(255) not null, recordType varchar(255) not null, userId varchar(255) not null, viewable bit not null, primary key (id), unique (contextId, recordType, userId));
