-- Force this to happen and report problems bu having a non failing SQL statement first


ALTER TABLE CALENDAR_EVENT ADD COLUMN RANGE_START INTEGER;
ALTER TABLE CALENDAR_EVENT ADD COLUMN RANGE_END INTEGER;

CREATE INDEX CALENDAR_EVENT_RSTART ON CALENDAR_EVENT(RANGE_START);
CREATE INDEX CALENDAR_EVENT_REND ON CALENDAR_EVENT(RANGE_END);
